import { TableFloorItem } from './types';

export const INITIAL_TABLES_DATA: TableFloorItem[] = [
  {
    id: 'T-01',
    number: '01',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-02',
    number: '02',
    capacity: 4,
    currentPartySize: 0,
    zone: 'Main Hall',
    status: 'Available',
    server: 'Jake R.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-03',
    number: '03',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-04',
    number: '04',
    capacity: 4,
    currentPartySize: 2,
    zone: 'Main Hall',
    status: 'Reserved',
    server: 'Jake R.',
    seatedTime: '7:00 PM',
    billAmount: 0.0,
  },
  {
    id: 'T-05',
    number: '05',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Reserved',
    server: 'Jake R.',
    seatedTime: '6:30 PM',
    billAmount: 0.0,
  },
  {
    id: 'T-06',
    number: '06',
    capacity: 4,
    currentPartySize: 0,
    zone: 'Main Hall',
    status: 'Available',
    server: 'Jake R.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-07',
    number: '07',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-08',
    number: '08',
    capacity: 4,
    currentPartySize: 4,
    zone: 'Main Hall',
    status: 'Reserved',
    server: 'Jake R.',
    seatedTime: '7:30 PM',
    billAmount: 0.0,
  },
  {
    id: 'T-09',
    number: '09',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-10',
    number: '10',
    capacity: 4,
    currentPartySize: 0,
    zone: 'Main Hall',
    status: 'Available',
    server: 'Jake R.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-11',
    number: '11',
    capacity: 4,
    currentPartySize: 2,
    zone: 'Main Hall',
    status: 'Reserved',
    server: 'Jake R.',
    seatedTime: '8:00 PM',
    billAmount: 0.0,
  },
  {
    id: 'T-12',
    number: '12',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-13',
    number: '13',
    capacity: 4,
    currentPartySize: 0,
    zone: 'Main Hall',
    status: 'Available',
    server: 'Jake R.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-14',
    number: '14',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Occupied',
    server: 'Jake R.',
    seatedTime: '1:15 PM',
    billAmount: 68.5,
  },
  {
    id: 'T-15',
    number: '15',
    capacity: 4,
    currentPartySize: 3,
    zone: 'Main Hall',
    status: 'Reserved',
    server: 'Jake R.',
    seatedTime: '8:30 PM',
    billAmount: 0.0,
  },
  {
    id: 'T-16',
    number: '16',
    capacity: 4,
    currentPartySize: 0,
    zone: 'Main Hall',
    status: 'Available',
    server: 'Jake R.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-17',
    number: '17',
    capacity: 6,
    currentPartySize: 5,
    zone: 'Patio',
    status: 'Occupied',
    server: 'Sarah M.',
    seatedTime: '12:45 PM',
    billAmount: 112.0,
  },
  {
    id: 'T-18',
    number: '18',
    capacity: 2,
    currentPartySize: 0,
    zone: 'Patio',
    status: 'Available',
    server: 'Sarah M.',
    seatedTime: '—',
    billAmount: 0.0,
  },
  {
    id: 'T-19',
    number: '19',
    capacity: 4,
    currentPartySize: 4,
    zone: 'Patio',
    status: 'Occupied',
    server: 'Sarah M.',
    seatedTime: '1:30 PM',
    billAmount: 89.0,
  },
  {
    id: 'T-20',
    number: '20',
    capacity: 2,
    currentPartySize: 0,
    zone: 'Bar Area',
    status: 'Available',
    server: 'Alex T.',
    seatedTime: '—',
    billAmount: 0.0,
  },
];
