import {
  MetricCardData,
  RevenueDataPoint,
  BusinessHealthMetric,
  RestaurantItem,
  BranchItem,
  PermissionRole,
  PaymentTransaction,
} from './types';

export const INITIAL_METRICS: MetricCardData[] = [
  {
    title: 'Total Restaurants',
    value: '3',
    change: '+1 this month',
    isPositive: true,
  },
  {
    title: 'Total Branches',
    value: '4',
    change: 'Across 3 restaurants',
    isPositive: true,
  },
  {
    title: 'Total Staff',
    value: '48',
    change: '+6 this month',
    isPositive: true,
  },
  {
    title: 'Revenue',
    value: '$2M',
    change: '+12.4% vs last month',
    isPositive: true,
  },
];

export const REVENUE_PERIOD_DATA: Record<string, RevenueDataPoint[]> = {
  Week: [
    { day: 'Mon', value: 8.5, formatted: '$8,500' },
    { day: 'Tue', value: 12.0, formatted: '$12,000' },
    { day: 'Wed', value: 10.4, formatted: '$10,400' },
    { day: 'Thu', value: 14.8, formatted: '$14,800' },
    { day: 'Fri', value: 18.2, formatted: '$18,200' },
    { day: 'Sat', value: 19.5, formatted: '$19,500' },
    { day: 'Sun', value: 16.0, formatted: '$16,000' },
  ],
  Month: [
    { day: 'Week 1', value: 85.0, formatted: '$85,000' },
    { day: 'Week 2', value: 112.5, formatted: '$112,500' },
    { day: 'Week 3', value: 98.4, formatted: '$98,400' },
    { day: 'Week 4', value: 145.2, formatted: '$145,200' },
  ],
  Year: [
    { day: 'Q1', value: 340, formatted: '$340,000' },
    { day: 'Q2', value: 480, formatted: '$480,000' },
    { day: 'Q3', value: 520, formatted: '$520,000' },
    { day: 'Q4', value: 660, formatted: '$660,000' },
  ],
  All: [
    { day: '2023', value: 1100, formatted: '$1.1M' },
    { day: '2024', value: 1540, formatted: '$1.54M' },
    { day: '2025', value: 1890, formatted: '$1.89M' },
    { day: '2026', value: 2000, formatted: '$2.0M' },
  ],
};

export const BUSINESS_HEALTH_METRICS: BusinessHealthMetric[] = [
  { name: 'Revenue', score: 94, color: 'bg-emerald-500' },
  { name: 'Operations', score: 90, color: 'bg-indigo-500' },
  { name: 'Customer Sat.', score: 96, color: 'bg-emerald-500' },
  { name: 'Staff', score: 88, color: 'bg-indigo-500' },
  { name: 'Profitability', score: 91, color: 'bg-emerald-500' },
];

export const MOCK_RESTAURANTS: RestaurantItem[] = [
  {
    id: 'rest-1',
    name: 'Tavonza Kitchen',
    description: 'Modern dining with seasonal plates.',
    tagline: 'Modern dining with seasonal plates.',
    cuisine: 'Contemporary Modern Dining',
    manager: 'Robert Geo',
    contactNumber: '+4045017715',
    email: 'hello@tavonza.com',
    address: 'Cusseta, Georgia',
    city: 'Cusseta',
    branchesCount: 2,
    staffCount: 24,
    monthlyRevenue: '$148,250',
    rating: 4.9,
    status: 'Active',
  },
  {
    id: 'rest-2',
    name: 'Ember & Grain',
    description: 'Wood-fired cooking and artisan bakery.',
    tagline: 'Wood-fired cooking and artisan bakery.',
    cuisine: 'Wood-fired Artisan & Bakery',
    manager: 'Sarah Ahmed',
    contactNumber: '+14155552671',
    email: 'ember@tavonza.com',
    address: '42 Ocean Marina Pier',
    city: 'Harbor Bay',
    branchesCount: 1,
    staffCount: 14,
    monthlyRevenue: '$82,400',
    rating: 4.8,
    status: 'Active',
  },
  {
    id: 'rest-3',
    name: 'Kori Social',
    description: 'Contemporary Maxican food & cocktails',
    tagline: 'Contemporary Maxican food & cocktails',
    cuisine: 'Mexican Contemporary & Bar',
    manager: 'Alex Thorne',
    contactNumber: '+12125559812',
    email: 'kori@tavonza.com',
    address: '780 Uptown Boulevard',
    city: 'Midtown West',
    branchesCount: 1,
    staffCount: 10,
    monthlyRevenue: '$64,150',
    rating: 4.7,
    status: 'Setup',
  },
];

export const MOCK_BRANCHES: BranchItem[] = [
  {
    id: 'br-1',
    restaurantId: 'rest-1',
    restaurantName: 'Tavonza Kitchen',
    name: 'Georgia Flagship',
    location: 'Cusseta, Georgia',
    manager: 'Nobin Mille',
    hours: '09:00 – 23:00',
    openingTime: '09:00',
    closingTime: '23:00',
    contactNumber: '992548756',
    tablesCount: 18,
    occupancy: 78,
    status: 'Active',
    kitchenSync: 'Online',
    monthlyRevenue: '$92,400',
  },
  {
    id: 'br-2',
    restaurantId: 'rest-1',
    restaurantName: 'Tavonza Kitchen',
    name: 'Florida Flagship',
    location: 'Pompano Beach, Florida',
    manager: 'Samira Khan',
    hours: '10:00 – 22:30',
    openingTime: '10:00',
    closingTime: '22:30',
    contactNumber: '+19545558910',
    tablesCount: 14,
    occupancy: 64,
    status: 'Active',
    kitchenSync: 'Online',
    monthlyRevenue: '$55,850',
  },
  {
    id: 'br-3',
    restaurantId: 'rest-2',
    restaurantName: 'Ember & Grain',
    name: 'Illinois Flagship',
    location: 'Pompano Beach, Florida',
    manager: 'Mikel',
    hours: '08:00 – 23:30',
    openingTime: '08:00',
    closingTime: '23:30',
    contactNumber: '+13125550192',
    tablesCount: 24,
    occupancy: 82,
    status: 'Active',
    kitchenSync: 'Online',
    monthlyRevenue: '$82,400',
  },
  {
    id: 'br-4',
    restaurantId: 'rest-3',
    restaurantName: 'Kori Social',
    name: 'Texas Flagship',
    location: 'Pompano Beach, Florida',
    manager: 'Glory',
    hours: '11:00 – 23:00',
    openingTime: '11:00',
    closingTime: '23:00',
    contactNumber: '+15125557821',
    tablesCount: 14,
    occupancy: 50,
    status: 'Setup',
    kitchenSync: 'Online',
    monthlyRevenue: '$41,200',
  },
];

export const MOCK_PERMISSIONS: PermissionRole[] = [
  {
    id: 'role-super-admin',
    title: 'Platform Owner / Super Admin',
    usersCount: 2,
    badgeColor: 'bg-amber-400/20 text-amber-300 border-amber-400/30',
    description: 'Full unconstrained platform control, billing, schema management, and organization provisioning.',
    capabilities: [
      'Full Database Access',
      'Manage All Organizations',
      'AI Gateway Configuration',
      'Billing & SaaS Subscriptions',
      'System Audit Logging',
    ],
  },
  {
    id: 'role-org-admin',
    title: 'Organization Administrator',
    usersCount: 5,
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Autonomous control over restaurants, branches, brand menus, staff rosters, and financial payouts.',
    capabilities: [
      'Create & Edit Restaurants',
      'Manage Branches & Tables',
      'Configure POS Terminals',
      'View Cross-Branch Analytics',
      'Staff Payroll & Shifts',
    ],
  },
  {
    id: 'role-branch-manager',
    title: 'Branch General Manager',
    usersCount: 8,
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Direct management of branch floor operations, inventory replenishment, and live table allocations.',
    capabilities: [
      'Floor Plan & Table Status',
      'Live Order Reassignment',
      'Kitchen/Bar Routing Rules',
      'Discounts & Comp Authority',
      'Daily Settlement Reports',
    ],
  },
  {
    id: 'role-kitchen-lead',
    title: 'Kitchen & Bar Lead',
    usersCount: 14,
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    description: 'KDS station operation, cooking ticket timers, recipe checks, and 86 item inventory marks.',
    capabilities: [
      'Station Ticket Dispatch',
      'Kitchen Display System (KDS)',
      'Item 86 Availability Toggle',
      'Recipe Spec Inspection',
    ],
  },
  {
    id: 'role-staff-server',
    title: 'Floor Server / Cashier',
    usersCount: 19,
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    description: 'Take guest orders, punch POS tickets, accept contactless payments, and trigger kitchen calls.',
    capabilities: [
      'POS Ticket Entry',
      'Table QR Ordering Assist',
      'Payment Terminal Processing',
      'Bill Split & Cash Drawer',
    ],
  },
];

export const MOCK_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'TXN-98421',
    restaurant: 'Tavonza Downtown HQ',
    branch: 'Main Atrium Branch',
    orderNumber: '#1048',
    amount: '$148.50',
    method: 'Stripe',
    status: 'Completed',
    timestamp: '2 mins ago',
  },
  {
    id: 'TXN-98420',
    restaurant: 'Tavonza Seaside Bistro',
    branch: 'Waterfront Terrace',
    orderNumber: '#1047',
    amount: '$89.00',
    method: 'Apple Pay',
    status: 'Completed',
    timestamp: '5 mins ago',
  },
  {
    id: 'TXN-98419',
    restaurant: 'Tavonza Downtown HQ',
    branch: 'Executive Sky Lounge',
    orderNumber: '#1046',
    amount: '$340.25',
    method: 'POS Terminal',
    status: 'Completed',
    timestamp: '14 mins ago',
  },
  {
    id: 'TXN-98418',
    restaurant: 'Tavonza Uptown Grill',
    branch: 'Midtown Tasting Room',
    orderNumber: '#1045',
    amount: '$56.70',
    method: 'QR Pay',
    status: 'Completed',
    timestamp: '22 mins ago',
  },
  {
    id: 'TXN-98417',
    restaurant: 'Tavonza Seaside Bistro',
    branch: 'Waterfront Terrace',
    orderNumber: '#1044',
    amount: '$210.00',
    method: 'Stripe',
    status: 'Completed',
    timestamp: '35 mins ago',
  },
  {
    id: 'TXN-98416',
    restaurant: 'Tavonza Downtown HQ',
    branch: 'Main Atrium Branch',
    orderNumber: '#1043',
    amount: '$45.00',
    method: 'QR Pay',
    status: 'Pending',
    timestamp: '42 mins ago',
  },
];
