import { PlanDefinition, InvoiceItem } from './types';

export const PLANS: PlanDefinition[] = [
  {
    id: 'basic',
    name: 'Basic',
    price: 199,
    billingPeriod: 'month',
    tagline: 'The essentials for a growing restaurant.',
    restaurantsLimit: 1,
    branchesLimit: 5,
    staffLimit: 15,
    features: [
      '1 restaurant',
      '5 branches',
      '15 staff members',
      'Core order management',
      'Standard reports',
      'Email support',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 499,
    billingPeriod: 'month',
    tagline: 'More control for multi-branch teams.',
    restaurantsLimit: 5,
    branchesLimit: 20,
    staffLimit: 50,
    features: [
      '5 restaurants',
      '20 branches',
      '50 staff members',
      'Advanced analytics',
      'Inventory automation',
      'Priority support',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 599,
    billingPeriod: 'month',
    tagline: 'Scale operations without compromise.',
    restaurantsLimit: 'Unlimited',
    branchesLimit: 'Unlimited',
    staffLimit: 200,
    features: [
      'Unlimited restaurants',
      'Unlimited branches',
      '200 staff members',
      'Custom roles & access',
      'API integrations',
      'Dedicated manager',
    ],
  },
];

export const INITIAL_INVOICES: InvoiceItem[] = [
  {
    id: 'INV-2026-10-15',
    date: '15 Oct 2026',
    plan: 'Pro Plan',
    amount: '$499',
    status: 'Paid',
    paymentMethod: 'Visa ending in 4242',
    subtotal: '$475.24',
    vat: '$23.76',
  },
  {
    id: 'INV-2026-09-15',
    date: '15 Sep 2026',
    plan: 'Pro Plan',
    amount: '$499',
    status: 'Paid',
    paymentMethod: 'Visa ending in 4242',
    subtotal: '$475.24',
    vat: '$23.76',
  },
  {
    id: 'INV-2026-08-15',
    date: '15 Aug 2026',
    plan: 'Pro Plan',
    amount: '$499',
    status: 'Paid',
    paymentMethod: 'Visa ending in 4242',
    subtotal: '$475.24',
    vat: '$23.76',
  },
  {
    id: 'INV-2026-07-15',
    date: '15 Jul 2026',
    plan: 'Pro Plan',
    amount: '$499',
    status: 'Paid',
    paymentMethod: 'Visa ending in 4242',
    subtotal: '$475.24',
    vat: '$23.76',
  },
];
