import { TransactionItem } from './types';

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: 'tx-15',
    txId: 'TX-10590',
    orderNumber: '#10590',
    method: 'Visa Card',
    cashier: 'Emily W.',
    status: 'Paid',
    amount: 52.40,
    time: '12:45 PM',
    customerName: 'Sarah Jenkins',
    itemsCount: 3,
  },
  {
    id: 'tx-14',
    txId: 'TX-10589',
    orderNumber: '#10589',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '12:42 PM',
    customerName: 'David Kim',
    itemsCount: 2,
  },
  {
    id: 'tx-13',
    txId: 'TX-10588',
    orderNumber: '#10588',
    method: 'QR Payment',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '12:35 PM',
    customerName: 'Elena Rostova',
    itemsCount: 4,
  },
  {
    id: 'tx-12',
    txId: 'TX-10587',
    orderNumber: '#10587',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '12:28 PM',
    customerName: 'Michael Chang',
    itemsCount: 2,
  },
  {
    id: 'tx-11',
    txId: 'TX-10586',
    orderNumber: '#10586',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '12:15 PM',
    customerName: 'Alex Mercer',
    itemsCount: 3,
  },
  {
    id: 'tx-10',
    txId: 'TX-10585',
    orderNumber: '#10585',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '12:08 PM',
    customerName: 'Jessica Taylor',
    itemsCount: 2,
  },
  {
    id: 'tx-9',
    txId: 'TX-10584',
    orderNumber: '#10584',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Failed',
    amount: 73.80,
    time: '11:55 AM',
    customerName: 'Marcus Vance',
    itemsCount: 5,
  },
  {
    id: 'tx-8',
    txId: 'TX-10583',
    orderNumber: '#10583',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '11:42 AM',
    customerName: 'Chloe Bennett',
    itemsCount: 3,
  },
  {
    id: 'tx-7',
    txId: 'TX-10582',
    orderNumber: '#10582',
    method: 'Visa Card',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 52.40,
    time: '11:30 AM',
    customerName: 'Robert Lang',
    itemsCount: 2,
  },
  {
    id: 'tx-6',
    txId: 'TX-10581',
    orderNumber: '#10581',
    method: 'MasterCard',
    cashier: 'Emily W.',
    status: 'Pending',
    amount: 46.50,
    time: '11:15 AM',
    customerName: 'Lucas Grey',
    itemsCount: 4,
  },
  {
    id: 'tx-5',
    txId: 'TX-10580',
    orderNumber: '#10580',
    method: 'Cash',
    cashier: 'John Carter',
    status: 'Refunded',
    amount: 18.50,
    time: '11:02 AM',
    customerName: 'Sophie Turner',
    itemsCount: 1,
  },
  {
    id: 'tx-4',
    txId: 'TX-10579',
    orderNumber: '#10579',
    method: 'QR Payment',
    cashier: 'Emily W.',
    status: 'Paid',
    amount: 38.90,
    time: '10:48 AM',
    customerName: 'Ethan Wright',
    itemsCount: 2,
  },
  {
    id: 'tx-3',
    txId: 'TX-10578',
    orderNumber: '#10578',
    method: 'Apple Pay',
    cashier: 'John Carter',
    status: 'Paid',
    amount: 64.20,
    time: '10:30 AM',
    customerName: 'Hannah Abbott',
    itemsCount: 4,
  },
  {
    id: 'tx-2',
    txId: 'TX-10577',
    orderNumber: '#10577',
    method: 'Visa Card',
    cashier: 'Emily W.',
    status: 'Pending',
    amount: 67.20,
    time: '10:15 AM',
    customerName: 'Liam Davis',
    itemsCount: 3,
  },
  {
    id: 'tx-1',
    txId: 'TX-10576',
    orderNumber: '#10576',
    method: 'MasterCard',
    cashier: 'John Carter',
    status: 'Failed',
    amount: 42.00,
    time: '10:00 AM',
    customerName: 'Zoe Kravitz',
    itemsCount: 2,
  },
];
