import { MarketplaceApp, MarketplaceCategory } from './types';

export const MARKETPLACE_CATEGORIES: MarketplaceCategory[] = [
  'All Tiers',
  'Delivery',
  'Reservations',
  'Reviews',
  'Accounting',
  'Marketing',
  'Payments',
  'Communication',
];

export const INITIAL_MARKETPLACE_APPS: MarketplaceApp[] = [
  {
    id: 'app-uber-eats',
    name: 'Uber Eats Integration',
    category: 'Delivery',
    badge: 'Popular',
    description: 'Sync your menu and receive Uber Eats orders directly in your POS.',
    price: 'Free',
    rating: 4.9,
    reviewsCount: 342,
    isInstalled: true,
    developer: 'Uber Technologies, Inc.',
    logoBg: 'bg-emerald-500/10',
    logoColor: 'text-emerald-400',
    permissions: ['Read menu items', 'Inject incoming orders', 'Update stock availability'],
    lastSync: '1 min ago',
  },
  {
    id: 'app-doordash',
    name: 'DoorDash Connect',
    category: 'Delivery',
    badge: '● On Shift',
    description: 'Real-time order sync and delivery tracking for DoorDash orders.',
    price: 'Free',
    rating: 4.7,
    reviewsCount: 289,
    isInstalled: true,
    developer: 'DoorDash Inc.',
    logoBg: 'bg-red-500/10',
    logoColor: 'text-red-400',
    permissions: ['POS order injection', 'Kitchen ticket printing', 'Delivery driver ETA tracking'],
    lastSync: '4 min ago',
  },
  {
    id: 'app-opentable',
    name: 'OpenTable Reservations',
    category: 'Reservations',
    badge: 'Top Rated',
    description: 'Accept and manage table reservations directly from OpenTable.',
    price: '$29/mo',
    rating: 4.9,
    reviewsCount: 512,
    isInstalled: false,
    developer: 'OpenTable, Inc.',
    logoBg: 'bg-rose-500/10',
    logoColor: 'text-rose-400',
    permissions: ['Read dining floor plans', 'Manage table statuses', 'Customer reservation alerts'],
  },
  {
    id: 'app-google-reviews',
    name: 'Google Reviews Auto-Reply',
    category: 'Reviews',
    badge: 'Popular',
    description: 'AI-powered responses to Google Reviews in your brand voice.',
    price: 'Free',
    rating: 4.9,
    reviewsCount: 420,
    isInstalled: true,
    developer: 'Google LLC Partner',
    logoBg: 'bg-blue-500/10',
    logoColor: 'text-blue-400',
    permissions: ['Read Google Business reviews', 'Post AI response drafts', 'Track sentiment scores'],
    lastSync: '12 min ago',
  },
  {
    id: 'app-quickbooks',
    name: 'QuickBooks Sync',
    category: 'Accounting',
    badge: '● On Shift',
    description: 'Automatically sync daily sales, expenses, and payroll to QuickBooks.',
    price: 'Free',
    rating: 4.7,
    reviewsCount: 198,
    isInstalled: true,
    developer: 'Intuit QuickBooks',
    logoBg: 'bg-green-500/10',
    logoColor: 'text-green-400',
    permissions: ['Read sales ledger', 'Tax breakdown export', 'COGS category mapping'],
    lastSync: '25 min ago',
  },
  {
    id: 'app-mailchimp',
    name: 'Mailchimp Marketing',
    category: 'Marketing',
    badge: 'Top Rated',
    description: 'Connect your customer list to Mailchimp for automated email campaigns.',
    price: '$29/mo',
    rating: 4.9,
    reviewsCount: 310,
    isInstalled: false,
    developer: 'Mailchimp by Intuit',
    logoBg: 'bg-amber-500/10',
    logoColor: 'text-amber-400',
    permissions: ['Sync loyalty subscriber emails', 'Automate birthday emails', 'Track coupon redemptions'],
  },
  {
    id: 'app-yelp',
    name: 'Yelp Business',
    category: 'Reviews',
    badge: 'Popular',
    description: 'Manage Yelp profile, respond to reviews, and view analytics.',
    price: 'Free',
    rating: 4.9,
    reviewsCount: 260,
    isInstalled: false,
    developer: 'Yelp Inc.',
    logoBg: 'bg-red-500/10',
    logoColor: 'text-red-400',
    permissions: ['Read customer ratings', 'Post review replies', 'Sync menu photos'],
  },
  {
    id: 'app-stripe',
    name: 'Stripe Payments',
    category: 'Payments',
    badge: '● On Shift',
    description: 'Accept card payments online and in-person with full reconciliation.',
    price: '2.9% + 30¢',
    rating: 4.7,
    reviewsCount: 780,
    isInstalled: true,
    developer: 'Stripe Inc.',
    logoBg: 'bg-violet-500/10',
    logoColor: 'text-violet-400',
    permissions: ['Process card payouts', 'Reconcile batch settlements', 'Fraud detection sentinel'],
    lastSync: 'Just now',
  },
  {
    id: 'app-whatsapp',
    name: 'WhatsApp Business',
    category: 'Communication',
    badge: 'Top Rated',
    description: 'Send order confirmations and loyalty updates via WhatsApp.',
    price: 'Free',
    rating: 4.9,
    reviewsCount: 654,
    isInstalled: false,
    developer: 'Meta Business Platform',
    logoBg: 'bg-emerald-500/10',
    logoColor: 'text-emerald-400',
    permissions: ['Send transactional SMS/WhatsApp', 'Receive guest table requests', 'Automated chat bot'],
  },
  {
    id: 'app-resy',
    name: 'Resy Hospitality Sync',
    category: 'Reservations',
    badge: 'Popular',
    description: 'Sync dining room covers, guest preferences, and VIP waitlists with Resy.',
    price: '$39/mo',
    rating: 4.8,
    reviewsCount: 175,
    isInstalled: false,
    developer: 'Resy Network, Inc.',
    logoBg: 'bg-red-500/10',
    logoColor: 'text-red-400',
    permissions: ['Live table pacing', 'Guest dining history', 'Reservation deposit tracking'],
  },
  {
    id: 'app-xero',
    name: 'Xero Accounting Bridge',
    category: 'Accounting',
    badge: 'Top Rated',
    description: 'Seamless cloud bookkeeping and invoice reconciliation for restaurant supplies.',
    price: '$19/mo',
    rating: 4.8,
    reviewsCount: 220,
    isInstalled: false,
    developer: 'Xero Software',
    logoBg: 'bg-sky-500/10',
    logoColor: 'text-sky-400',
    permissions: ['Daily sales sync', 'Invoice automated capture', 'Tax compliance exports'],
  },
  {
    id: 'app-square',
    name: 'Square Terminal & Pay',
    category: 'Payments',
    badge: 'Popular',
    description: 'Accept contactless pay, chip cards, and Apple Pay with Square hardware.',
    price: '2.6% + 10¢',
    rating: 4.9,
    reviewsCount: 630,
    isInstalled: false,
    developer: 'Block, Inc.',
    logoBg: 'bg-zinc-500/10',
    logoColor: 'text-zinc-400',
    permissions: ['Hardware terminal sync', 'Split-check processing', 'Offline payment caching'],
  },
  {
    id: 'app-grubhub',
    name: 'Grubhub Direct Orders',
    category: 'Delivery',
    badge: '● On Shift',
    description: 'Direct kitchen ticket printing and automated delivery dispatch with Grubhub.',
    price: 'Free',
    rating: 4.6,
    reviewsCount: 390,
    isInstalled: false,
    developer: 'Grubhub Holdings Inc.',
    logoBg: 'bg-orange-500/10',
    logoColor: 'text-orange-400',
    permissions: ['POS order injection', 'Courier ETA tracking', 'Automated refund approvals'],
  },
  {
    id: 'app-twilio',
    name: 'Twilio SMS Host Sentinel',
    category: 'Communication',
    badge: 'Top Rated',
    description: 'Send two-way SMS table notifications and waitlist status alerts to diners.',
    price: '$0.0079/msg',
    rating: 4.9,
    reviewsCount: 410,
    isInstalled: false,
    developer: 'Twilio Inc.',
    logoBg: 'bg-red-500/10',
    logoColor: 'text-red-400',
    permissions: ['Two-way SMS messaging', 'Diner confirmation tracking', 'Broadcast announcements'],
  },
  {
    id: 'app-klaviyo',
    name: 'Klaviyo Restaurant CRM',
    category: 'Marketing',
    badge: 'Popular',
    description: 'Segment diners by spend tier and trigger automated SMS and email campaigns.',
    price: '$45/mo',
    rating: 4.8,
    reviewsCount: 295,
    isInstalled: false,
    developer: 'Klaviyo, Inc.',
    logoBg: 'bg-amber-500/10',
    logoColor: 'text-amber-400',
    permissions: ['Customer lifetime value sync', 'Predictive churn triggers', 'Omnichannel marketing'],
  },
];
