import {
  StatCardData,
  FinancialPulseMetric,
  OrderItem,
  TopMenuItem,
  ReservationItem,
  AIRecommendation,
  InventoryAlert,
  ReviewItem,
  MarketingCampaign,
  SupplierItem,
} from './types';

export const mockStatCards: StatCardData[] = [
  {
    title: "Today's Revenue",
    value: "$12,840",
    change: "▲ +12.8%",
    isPositive: true,
    subtext: "Compared to yesterday",
    accentColor: "yellow",
  },
  {
    title: "Orders Today",
    value: "328",
    change: "+36 Orders",
    isPositive: true,
    subtext: "Orders Today",
    accentColor: "blue",
    breakdown: [
      { label: "✓ 301 Done", value: "301", color: "text-green-500" },
      { label: "○ 27 Pending", value: "27", color: "text-amber-500" },
    ],
  },
  {
    title: "Average Order Value",
    value: "$39.40",
    change: "+$2.60",
    isPositive: true,
    subtext: "Compared to last week",
    accentColor: "purple",
  },
  {
    title: "Customers Served",
    value: "284",
    change: "▲ +18%",
    isPositive: true,
    subtext: "Compared to yesterday",
    accentColor: "green",
  },
  {
    title: "Active Tables",
    value: "22/30",
    change: "Occupied",
    isPositive: true,
    subtext: "Active Tables",
    accentColor: "teal",
    breakdown: [
      { label: "● 22 Busy", value: "22", color: "text-teal-400" },
      { label: "○ 8 Free", value: "8", color: "text-zinc-400" },
    ],
  },
  {
    title: "Kitchen Queue",
    value: "18 Orders",
    change: "● Live",
    isPositive: true,
    subtext: "Orders Today",
    accentColor: "orange",
    breakdown: [
      { label: "▶ 11 Prep", value: "11", color: "text-orange-400" },
      { label: "⏱ 7 Wait", value: "7", color: "text-blue-400" },
    ],
  },
];

export const mockFinancialPulse: FinancialPulseMetric[] = [
  {
    title: "Net Profit",
    value: "$3,840",
    badge: "▲ +8.4%",
    isPositive: true,
    period: "Today",
    status: "Healthy margin",
    iconColor: "text-green-500",
  },
  {
    title: "Cash Flow",
    value: "+$23,000",
    badge: "▲ Monthly surplus",
    isPositive: true,
    period: "Jul 2025",
    status: "Positive liquidity",
    iconColor: "text-indigo-400",
  },
  {
    title: "Food Cost %",
    value: "28.4%",
    badge: "▲ Target: 30%",
    isPositive: true,
    period: "Below target ✓",
    status: "Optimized",
    iconColor: "text-amber-500",
  },
  {
    title: "Labour Cost %",
    value: "24.1%",
    badge: "▲ Target: 25%",
    isPositive: true,
    period: "Below target ✓",
    status: "Efficient staffing",
    iconColor: "text-pink-500",
  },
  {
    title: "Inventory Value",
    value: "$14,280",
    badge: "▼ -$640 this week",
    isPositive: false,
    period: "Current stock",
    status: "Turnover normal",
    iconColor: "text-cyan-500",
  },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: "rec-1",
    icon: "🍔",
    title: "Promote Signature Burgers",
    category: "Revenue",
    categoryColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    description: "Demand is expected to increase during lunch.",
    impact: "+$180 est. revenue boost",
    actionText: "Launch Promo",
  },
  {
    id: "rec-2",
    icon: "🧀",
    title: "Restock Mozzarella Cheese",
    category: "Urgent",
    categoryColor: "bg-rose-500/10 text-rose-400 border-rose-500/20",
    description: "Current inventory will not support tomorrow's forecast.",
    impact: "Prevents 8 pizza out-of-stocks",
    actionText: "Order Supply",
  },
  {
    id: "rec-3",
    icon: "👨‍🍳",
    title: "Assign One More Waiter",
    category: "Operations",
    categoryColor: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    description: "Floor 2 is expected to experience heavy traffic.",
    impact: "Reduces table wait time by 4m",
    actionText: "Assign Shift",
  },
  {
    id: "rec-4",
    icon: "🎯",
    title: "Launch a Dessert Promotion",
    category: "Revenue",
    categoryColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    description: "Combo meal customers are likely to add desserts.",
    impact: "+14% AOV potential",
    actionText: "Activate Push",
  },
];

export const mockInventoryAlerts: InventoryAlert[] = [
  {
    id: "inv-1",
    item: "Mozzarella Cheese",
    level: "Critical",
    percentage: 16,
    color: "bg-rose-500",
    currentStock: "3.2 kg",
    minRequired: "20.0 kg",
  },
  {
    id: "inv-2",
    item: "Chicken Breast",
    level: "Low",
    percentage: 38,
    color: "bg-amber-500",
    currentStock: "8.5 kg",
    minRequired: "22.0 kg",
  },
  {
    id: "inv-3",
    item: "Soft Drinks",
    level: "Restock",
    percentage: 28,
    color: "bg-amber-500",
    currentStock: "42 cans",
    minRequired: "150 cans",
  },
  {
    id: "inv-4",
    item: "Olive Oil",
    level: "Recommended",
    percentage: 54,
    color: "bg-indigo-500",
    currentStock: "6.0 L",
    minRequired: "10.0 L",
  },
];

export const mockRecentOrders: OrderItem[] = [
  {
    id: "#10482",
    table: "T-08",
    customer: "Emma Wilson",
    status: "Preparing",
    total: "$46.50",
    time: "2m ago",
    itemsCount: 3,
  },
  {
    id: "#10481",
    table: "T-04",
    customer: "James Chen",
    status: "Ready",
    total: "$68.20",
    time: "7m ago",
    itemsCount: 4,
  },
  {
    id: "#10480",
    table: "T-11",
    customer: "Sarah Miller",
    status: "Preparing",
    total: "$32.90",
    time: "11m ago",
    itemsCount: 2,
  },
  {
    id: "#10479",
    table: "T-02",
    customer: "Lucas Vance",
    status: "Preparing",
    total: "$89.00",
    time: "14m ago",
    itemsCount: 5,
  },
  {
    id: "#10478",
    table: "T-15",
    customer: "Elena Rostova",
    status: "Ready",
    total: "$54.30",
    time: "18m ago",
    itemsCount: 3,
  },
];

export const mockTopMenuItems: TopMenuItem[] = [
  {
    rank: 1,
    name: "Classic Burger",
    revenue: "$2,480",
    soldCount: 124,
    percentage: 88,
    category: "Mains",
  },
  {
    rank: 2,
    name: "Chicken Pizza",
    revenue: "$2,156",
    soldCount: 98,
    percentage: 72,
    category: "Pizza",
  },
  {
    rank: 3,
    name: "Alfredo Pasta",
    revenue: "$1,520",
    soldCount: 76,
    percentage: 58,
    category: "Pasta",
  },
  {
    rank: 4,
    name: "Caesar Salad",
    revenue: "$975",
    soldCount: 65,
    percentage: 45,
    category: "Salads",
  },
  {
    rank: 5,
    name: "Chocolate Brownie",
    revenue: "$660",
    soldCount: 44,
    percentage: 32,
    category: "Desserts",
  },
];

export const mockReservations: ReservationItem[] = [
  {
    id: "res-1",
    time: "6:30 PM",
    status: "confirmed",
    guestName: "Smith Party",
    table: "T-05",
    guests: 6,
    notes: "Anniversary dinner · Window table",
  },
  {
    id: "res-2",
    time: "7:00 PM",
    status: "confirmed",
    guestName: "Emma Wilson",
    table: "T-12",
    guests: 2,
    notes: "Quiet corner requested",
  },
  {
    id: "res-3",
    time: "6:30 PM",
    status: "pending",
    guestName: "Johnson Group",
    table: "T-18",
    guests: 8,
    notes: "Corporate team gathering",
  },
  {
    id: "res-4",
    time: "6:30 PM",
    status: "confirmed",
    guestName: "Chen Family",
    table: "T-07",
    guests: 4,
    notes: "Highchair needed",
  },
  {
    id: "res-5",
    time: "8:30 PM",
    status: "confirmed",
    guestName: "Birthday Party",
    table: "T-22",
    guests: 12,
    notes: "Custom cake storage needed",
  },
];

export const mockReviews: ReviewItem[] = [
  {
    id: "rev-1",
    author: "Emma W.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    rating: 5,
    timeAgo: "2h ago",
    content: "Amazing food and service! The Classic Burger is absolutely perfect.",
    sentiment: "positive",
  },
  {
    id: "rev-2",
    author: "James C.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    rating: 5,
    timeAgo: "4h ago",
    content: "Best pasta in the city. Staff is incredibly attentive and warm.",
    sentiment: "positive",
  },
  {
    id: "rev-3",
    author: "Sophia M.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    rating: 4,
    timeAgo: "Yesterday",
    content: "Great atmosphere and food. The wait time was a bit long during peak lunch.",
    sentiment: "neutral",
  },
];

export const mockMarketingCampaigns: MarketingCampaign[] = [
  {
    id: "camp-1",
    name: "Weekend Burger",
    channel: "SMS · 840 sent",
    sentCount: 840,
    openRate: 72,
    openRateTrend: "up",
    revenue: "$2,340",
  },
  {
    id: "camp-2",
    name: "VIP Dinner",
    channel: "Email · 220 sent",
    sentCount: 220,
    openRate: 68,
    openRateTrend: "up",
    revenue: "$4,800",
  },
  {
    id: "camp-3",
    name: "Feedback Req.",
    channel: "SMS · 380 sent",
    sentCount: 380,
    openRate: 48,
    openRateTrend: "down",
    revenue: "—",
  },
];

export const mockSuppliers: SupplierItem[] = [
  {
    id: "sup-1",
    name: "Fresh Produce Co.",
    category: "Organic Vegetables & Fruit",
    status: "Active",
    nextDelivery: "Tomorrow, 7:00 AM",
    pendingAmount: "$1,420.00",
  },
  {
    id: "sup-2",
    name: "Artisan Meats Ltd.",
    category: "Beef, Chicken & Cuts",
    status: "Pending Delivery",
    nextDelivery: "Tomorrow, 10:30 AM",
    pendingAmount: "$3,890.00",
  },
  {
    id: "sup-3",
    name: "Dairy & Cheese Hub",
    category: "Mozzarella, Cheddar, Cream",
    status: "Invoice Due",
    nextDelivery: "Friday, 8:00 AM",
    pendingAmount: "$840.00",
  },
];

export const revenueChartData = {
  Week: [
    { label: "Mon", revenue: 9.4, orders: 180, forecast: 9.0 },
    { label: "Tue", revenue: 11.2, orders: 210, forecast: 10.8 },
    { label: "Wed", revenue: 12.8, orders: 245, forecast: 12.5 },
    { label: "Thu", revenue: 14.1, orders: 270, forecast: 13.8 },
    { label: "Fri", revenue: 18.5, orders: 340, forecast: 17.9 },
    { label: "Sat", revenue: 21.4, orders: 390, forecast: 20.8 },
    { label: "Sun", revenue: 17.6, orders: 310, forecast: 17.0 },
  ],
  Month: [
    { label: "W1", revenue: 78.4, orders: 1450, forecast: 75.0 },
    { label: "W2", revenue: 84.2, orders: 1590, forecast: 82.0 },
    { label: "W3", revenue: 91.8, orders: 1720, forecast: 89.5 },
    { label: "W4", revenue: 98.6, orders: 1840, forecast: 95.0 },
  ],
  Year: [
    { label: "Q1", revenue: 290.0, orders: 5400, forecast: 280.0 },
    { label: "Q2", revenue: 340.5, orders: 6200, forecast: 330.0 },
    { label: "Q3", revenue: 380.2, orders: 7100, forecast: 375.0 },
    { label: "Q4", revenue: 410.8, orders: 7800, forecast: 400.0 },
  ],
  All: [
    { label: "2023", revenue: 890.0, orders: 18400, forecast: 850.0 },
    { label: "2024", revenue: 1150.0, orders: 22600, forecast: 1100.0 },
    { label: "2025", revenue: 1420.0, orders: 27900, forecast: 1380.0 },
  ],
};

export const forecastChartData = [
  { day: "Mon", actual: 12, predicted: 13, peak: false },
  { day: "Tue", actual: 14, predicted: 14.5, peak: false },
  { day: "Wed", actual: 16, predicted: 15.8, peak: false },
  { day: "Thu", actual: 0, predicted: 18.2, peak: false },
  { day: "Fri", actual: 0, predicted: 22.1, peak: true },
  { day: "Sat", actual: 0, predicted: 24.5, peak: true },
  { day: "Sun", actual: 0, predicted: 19.8, peak: false },
];

export const cashflowMonthlyData = [
  { month: "Feb", inflow: 42, outflow: 31, net: 11 },
  { month: "Mar", inflow: 54, outflow: 38, net: 16 },
  { month: "Apr", inflow: 61, outflow: 42, net: 19 },
  { month: "May", inflow: 58, outflow: 41, net: 17 },
  { month: "Jun", inflow: 74, outflow: 49, net: 25 },
  { month: "Jul", inflow: 88, outflow: 56, net: 32 },
];
