export const navToRoute: Record<string, string> = {
  'Dashboard': '/admin-dashboard/dashboard',
  'Orders': '/admin-dashboard/orders',
  'POS': '/admin-dashboard/pos',
  'QR Ordering': '/admin-dashboard/qr-ordering',
  'Menu': '/admin-dashboard/menu',
  'Tables': '/admin-dashboard/tables',
  'Kitchen Display': '/admin-dashboard/kitchen-display',
  'Bar Display': '/admin-dashboard/bar-display',
  'Inventory': '/admin-dashboard/inventory',
  'Recipes': '/admin-dashboard/recipes',
  'Suppliers': '/admin-dashboard/suppliers',
  'Payments': '/admin-dashboard/payments',
  'Finance': '/admin-dashboard/finance',
  'Analytics': '/admin-dashboard/analytics',
  'Business Intelligence': '/admin-dashboard/business-intelligence',
  'Employees': '/admin-dashboard/employees',
  'Customers': '/admin-dashboard/customers',
  'Restaurants': '/admin-dashboard/restaurants',
  'Loyalty': '/admin-dashboard/loyalty',
  'Marketing': '/admin-dashboard/marketing',
  'Reviews': '/admin-dashboard/reviews',
  'Documents': '/admin-dashboard/documents',
  'AI Agents': '/admin-dashboard/ai-agents',
  'Marketplace': '/admin-dashboard/marketplace',
  'Notifications': '/admin-dashboard/notifications',
  'Tavonza Card': '/admin-dashboard/tavonza-card',
  'Settings': '/admin-dashboard/settings',
};

export const routeToNav: Record<string, string> = {
  'dashboard': 'Dashboard',
  'orders': 'Orders',
  'pos': 'POS',
  'qr-ordering': 'QR Ordering',
  'menu': 'Menu',
  'tables': 'Tables',
  'kitchen-display': 'Kitchen Display',
  'bar-display': 'Bar Display',
  'inventory': 'Inventory',
  'recipes': 'Recipes',
  'suppliers': 'Suppliers',
  'payments': 'Payments',
  'finance': 'Finance',
  'analytics': 'Analytics',
  'business-intelligence': 'Business Intelligence',
  'employees': 'Employees',
  'customers': 'Customers',
  'restaurants': 'Restaurants',
  'loyalty': 'Loyalty',
  'marketing': 'Marketing',
  'reviews': 'Reviews',
  'documents': 'Documents',
  'ai-agents': 'AI Agents',
  'marketplace': 'Marketplace',
  'notifications': 'Notifications',
  'tavonza-card': 'Tavonza Card',
  'settings': 'Settings',
};
