import { BranchPerformanceRecord } from './types';

export const INITIAL_BRANCH_PERFORMANCE: BranchPerformanceRecord[] = [
  {
    id: 'br-georgia',
    name: 'Georgia Flagship',
    restaurant: 'Tavonza Kitchen',
    location: 'Cusseta, Georgia',
    orders: 1284,
    revenue: 4860000,
    revenueFormatted: '$ 4.86M',
    avgOrder: 3785,
    avgOrderFormatted: '$ 3,785',
    growth: 12.4,
    growthFormatted: '+12.4%',
    performance: 'Excellent',
    topItem: 'Prime Wagyu Ribeye (250g)',
    cardSplit: 74,
    cashSplit: 26,
  },
  {
    id: 'br-florida',
    name: 'Florida Flagship',
    restaurant: 'Tavonza Kitchen',
    location: 'Pompano Beach, Florida',
    orders: 934,
    revenue: 3190000,
    revenueFormatted: '$ 3.19M',
    avgOrder: 3415,
    avgOrderFormatted: '$ 3,415',
    growth: 8.1,
    growthFormatted: '+8.1%',
    performance: 'Strong',
    topItem: 'Pan-Seared Chilean Sea Bass',
    cardSplit: 68,
    cashSplit: 32,
  },
  {
    id: 'br-illinois',
    name: 'Illinois Flagship',
    restaurant: 'Ember & Grain',
    location: 'Pompano Beach, Florida',
    orders: 841,
    revenue: 2870000,
    revenueFormatted: '$ 2.87M',
    avgOrder: 3412,
    avgOrderFormatted: '$ 3,412',
    growth: 6.7,
    growthFormatted: '+6.7%',
    performance: 'Strong',
    topItem: 'Wood-Fired Truffle Margherita',
    cardSplit: 70,
    cashSplit: 30,
  },
  {
    id: 'br-texas',
    name: 'Texas Flagship',
    restaurant: 'Kori Social',
    location: 'Pompano Beach, Florida',
    orders: 612,
    revenue: 1820000,
    revenueFormatted: '$ 1.82M',
    avgOrder: 2973,
    avgOrderFormatted: '$ 2,973',
    growth: -1.2,
    growthFormatted: '-1.2%',
    performance: 'Review',
    topItem: 'Agave Smoked Barbacoa',
    cardSplit: 62,
    cashSplit: 38,
  },
];
