import { DashboardTable, ShiftKPIs, SpeedPreset, AdHocRequest, MenuItem } from './types';

export const initialShiftKPIs: ShiftKPIs = {
  allTables: 8,
  ready: 2,
  attention: 1,
  bill: 1,
  seated: 1,
  shiftStatus: 'Active',
  ordersInProgress: 14,
  nextPriorityTable: 'Table 12',
  nextPriorityOrder: '#10582 → T-12',
};

export const initialTables: DashboardTable[] = [
  {
    id: 't-1',
    tableNumber: 1,
    tableName: 'Table 1',
    zone: 'Main Dining',
    timeElapsed: '45m',
    status: 'ready',
    statusLabel: 'Order Ready To Serve',
    guestsCount: '2/2 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Anniversary celebration, Requested quiet corner.',
    orderId: '#10582',
    trayItems: [
      { id: 'item-1', name: '01x Truffle & Wild Mushroom Crostini', source: 'KITCHEN', verified: true },
      { id: 'item-2', name: '01x Truffle & Wild Mushroom Crostini', source: 'KITCHEN', verified: true },
      { id: 'item-3', name: '02x Wagyu Ribeye Steak Medium-Rare', source: 'KITCHEN', verified: true },
      { id: 'item-4', name: '01x Barolo Docg Red Wine 2018', source: 'BAR', verified: true },
    ],
  },
  {
    id: 't-2',
    tableNumber: 2,
    tableName: 'Table 2',
    zone: 'Main Dining',
    timeElapsed: '28m',
    status: 'attention',
    statusLabel: 'Need Attention',
    guestsCount: '4/4 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Customer requested Waiter, allergy Clarification on Sea Bass.',
    attentionReason: 'Severe Peanut & Crustacean allergy. Guest requested confirmation on cooking oil and garnish used for Pan-Seared Sea Bass.',
    orderId: '#10580',
    trayItems: [
      { id: 'item-2-1', name: '02x Pan-Seared Chilean Sea Bass', source: 'KITCHEN', verified: false },
      { id: 'item-2-2', name: '01x Burrata Salad w/ Heirloom Tomatoes', source: 'KITCHEN', verified: true },
    ],
  },
  {
    id: 't-3',
    tableNumber: 3,
    tableName: 'Table 3',
    zone: 'Main Dining',
    timeElapsed: '12m',
    status: 'preparing',
    statusLabel: 'Kitchen Preparing',
    guestsCount: '2/2 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Standard dining course, entrées currently on grill.',
    orderId: '#10584',
    trayItems: [
      { id: 'item-3-1', name: '02x Hand-Cut Fries w/ Truffle Mayo', source: 'KITCHEN', verified: false },
      { id: 'item-3-2', name: '01x Dry-Aged Burger with Cheddar', source: 'KITCHEN', verified: false },
    ],
  },
  {
    id: 't-4',
    tableNumber: 4,
    tableName: 'Table 4',
    zone: 'Main Dining',
    timeElapsed: '28m',
    status: 'bill',
    statusLabel: 'Bill Requested',
    guestsCount: '2/2 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Requested itemized Split receipt.',
    billAmount: '$148.50',
    orderId: '#10576',
    trayItems: [
      { id: 'item-4-1', name: '02x Espresso Macchiato', source: 'BAR', verified: true },
      { id: 'item-4-2', name: '01x Valrhona Chocolate Lava Cake', source: 'KITCHEN', verified: true },
    ],
  },
  {
    id: 't-5',
    tableNumber: 5,
    tableName: 'Table 5',
    zone: 'Patio Terrace',
    timeElapsed: '34m',
    status: 'ready',
    statusLabel: 'Order Ready To Serve',
    guestsCount: '3/4 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Requested extra sparkling water and fresh cracked pepper.',
    orderId: '#10588',
    trayItems: [
      { id: 'item-5-1', name: '02x Braised Lamb Shank w/ Polenta', source: 'KITCHEN', verified: true },
      { id: 'item-5-2', name: '01x Lobster Ravioli w/ Saffron Cream', source: 'KITCHEN', verified: true },
    ],
  },
  {
    id: 't-6',
    tableNumber: 6,
    tableName: 'Table 6',
    zone: 'Main Dining',
    timeElapsed: '08m',
    status: 'seated',
    statusLabel: 'Seated & Browsing',
    guestsCount: '2/2 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'First time guests, reviewing cocktail specials.',
    orderId: '#10591',
    trayItems: [],
  },
  {
    id: 't-7',
    tableNumber: 7,
    tableName: 'Table 7',
    zone: 'VIP Lounge',
    timeElapsed: '52m',
    status: 'preparing',
    statusLabel: 'Kitchen Preparing',
    guestsCount: '6/6 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Chef special 5-course tasting menu in progress.',
    orderId: '#10571',
    trayItems: [
      { id: 'item-7-1', name: '06x Duck Breast w/ Cherry Reduction', source: 'KITCHEN', verified: false },
    ],
  },
  {
    id: 't-8',
    tableNumber: 8,
    tableName: 'Table 8',
    zone: 'Main Dining',
    timeElapsed: '65m',
    status: 'bill',
    statusLabel: 'Dessert Recommended',
    guestsCount: '4/4 guests',
    waiterName: 'Alex Rivera ( you )',
    notes: 'Finished main course, ready for dessert recommendation.',
    billAmount: '$210.00',
    orderId: '#10565',
    trayItems: [
      { id: 'item-8-1', name: '02x Tiramisu Tradizionale', source: 'KITCHEN', verified: true },
    ],
  },
];

export const initialSpeedPresets: SpeedPreset[] = [
  { id: 'preset-1', title: 'Water Refill', department: 'Busser', priority: 'Normal', iconType: 'droplet' },
  { id: 'preset-2', title: 'Extra Napkins', department: 'Busser', priority: 'Normal', iconType: 'layers' },
  { id: 'preset-3', title: 'Extra Condiments', department: 'Kitchen', priority: 'Normal', iconType: 'utensils' },
  { id: 'preset-4', title: 'Table Spill Cleanup', department: 'Busser', priority: 'High', iconType: 'alert' },
  { id: 'preset-5', title: 'Severe Allergy', department: 'Kitchen', priority: 'Urgent', iconType: 'shield' },
  { id: 'preset-6', title: 'Call Restaurant Manager', department: 'Manager', priority: 'Urgent', iconType: 'phone' },
  { id: 'preset-7', title: 'Cutlery Replacement', department: 'Busser', priority: 'Normal', iconType: 'knife' },
  { id: 'preset-8', title: 'Expedite Course', department: 'Kitchen', priority: 'High', iconType: 'zap' },
];

export const initialAdHocRequests: AdHocRequest[] = [
  {
    id: 'req-1',
    tableName: 'Table 1',
    department: 'Kitchen',
    priority: 'Urgent',
    timestamp: 'Just Now',
    message: 'Customer requested Waiter, allergy Clarification on Sea Bass.',
    completed: false,
  },
  {
    id: 'req-2',
    tableName: 'Table 4',
    department: 'Busser',
    priority: 'High',
    timestamp: '1m Ago',
    message: 'Table 4 Spilled Wine on the Tablecloth, send busser Immediately.',
    completed: false,
  },
  {
    id: 'req-3',
    tableName: 'Table 2',
    department: 'Kitchen',
    priority: 'Normal',
    timestamp: '3m Ago',
    message: 'Requested extra rosemary butter and gluten-free bread basket.',
    completed: false,
  },
  {
    id: 'req-4',
    tableName: 'Table 6',
    department: 'Busser',
    priority: 'Normal',
    timestamp: '5m Ago',
    message: 'Requested sparkling water top-up and fresh chilled glasses.',
    completed: false,
  },
  {
    id: 'req-5',
    tableName: 'Table 3',
    department: 'Manager',
    priority: 'Urgent',
    timestamp: '7m Ago',
    message: 'VIP anniversary guests request manager visit for wine recommendation.',
    completed: false,
  },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: 'm-1',
    name: 'Truffle Margherita',
    price: 30.5,
    category: 'Starters',
    description: 'San Marzano tomatoes, fresh buffalo fior di latte, black summer truffle shavings, organic basil leaves.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-2',
    name: 'Burrata & Heirloom Tomatoes',
    price: 18.5,
    category: 'Starters',
    description: 'Imported Puglia burrata, balsamic glaze reduction, basil oil, toasted rosemary focaccia crisps.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-3',
    name: 'Wild Mushroom Crostini',
    price: 16.0,
    category: 'Starters',
    description: 'Sautéed foraged mushrooms, thyme, whipped garlic mascarpone, aged 24-month parmigiano-reggiano.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-4',
    name: 'Hamachi Crudo',
    price: 24.0,
    category: 'Starters',
    description: 'Sashimi-grade yellowtail, yuzu ponzu, sliced serrano peppers, white truffle oil essence.',
    dietaryTags: ['Gluten-Free'],
  },
  {
    id: 'm-5',
    name: 'Prime Wagyu Ribeye 12oz',
    price: 48.0,
    category: 'Mains',
    description: 'Miyazaki A5 Wagyu cut, roasted bone marrow butter, charred asparagus spears, black truffle potato puree.',
    dietaryTags: ['Gluten-Free'],
  },
  {
    id: 'm-6',
    name: 'Pan-Seared Chilean Sea Bass',
    price: 38.5,
    category: 'Mains',
    description: 'Wild-caught Chilean sea bass, saffron fumet broth, shaved baby fennel, butter-poached fingerling potatoes.',
    dietaryTags: ['Gluten-Free'],
  },
  {
    id: 'm-7',
    name: 'Handmade Truffle Gnocchi',
    price: 28.0,
    category: 'Mains',
    description: 'Piedmontese potato gnocchi, black truffle cream reduction, crispy sage leaves, micro herbs.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-8',
    name: 'Valrhona Chocolate Lava Cake',
    price: 16.0,
    category: 'Desserts',
    description: 'Warm molten bittersweet dark chocolate, bourbon vanilla bean gelato, dusted edible gold flake.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-9',
    name: 'Tiramisu Tradizionale',
    price: 14.0,
    category: 'Desserts',
    description: 'Espresso-soaked savoiardi ladyfingers, whipped zabaglione mascarpone, imported Valrhona cocoa.',
    dietaryTags: ['Vegetarian'],
  },
  {
    id: 'm-10',
    name: 'Barolo DOCG Red Wine 2018',
    price: 24.0,
    category: 'Cocktails & Wine',
    description: 'Piedmont vintage, bold structured tannins, rich notes of dried cherry, violets, and earthy leather.',
    dietaryTags: ['Gluten-Free'],
  },
  {
    id: 'm-11',
    name: 'Smoked Rosemary Old Fashioned',
    price: 18.0,
    category: 'Cocktails & Wine',
    description: 'Small-batch Kentucky bourbon, aromatic bitters, torched organic rosemary sprig, expressed orange oil.',
    dietaryTags: ['Chef Specials'],
  },
  {
    id: 'm-12',
    name: 'Sparkling Blood Orange Spritz',
    price: 9.5,
    category: 'Non-Alcoholic',
    description: 'Freshly squeezed Sicilian blood orange, premium fever-tree tonic, splash of club soda, fresh mint.',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
  },
  {
    id: 'm-13',
    name: 'Chef Tasting 5-Course Platter',
    price: 95.0,
    category: 'Chef Specials',
    description: 'Executive Chef degustation course with premium pairings, wagyu tartare, caviar, and black truffle pasta.',
    dietaryTags: ['Chef Specials'],
  },
];
