import { InventoryItem } from './types';

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'INV-001',
    name: 'Mozzarella Cheese',
    category: 'Dairy',
    currentStock: 4,
    unit: 'kg',
    minStock: 10,
    maxStock: 50,
    levelPercent: 12,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'Critical',
  },
  {
    id: 'INV-002',
    name: 'Chicken Breast',
    category: 'Protein',
    currentStock: 8,
    unit: 'kg',
    minStock: 15,
    maxStock: 60,
    levelPercent: 22,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'Low Stock',
  },
  {
    id: 'INV-003',
    name: 'Soft Drinks (Cans)',
    category: 'Beverages',
    currentStock: 12,
    unit: 'pcs',
    minStock: 48,
    maxStock: 200,
    levelPercent: 10,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Yesterday',
    status: 'Critical',
  },
  {
    id: 'INV-004',
    name: 'Wheat Flour',
    category: 'Dry Goods',
    currentStock: 45,
    unit: 'kg',
    minStock: 20,
    maxStock: 100,
    levelPercent: 55,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'In Stock',
  },
  {
    id: 'INV-005',
    name: 'Olive Oil',
    category: 'Condiments',
    currentStock: 18,
    unit: 'L',
    minStock: 10,
    maxStock: 40,
    levelPercent: 52,
    supplier: 'FreshDairy Co.',
    lastUpdated: '2 days ago',
    status: 'In Stock',
  },
  {
    id: 'INV-006',
    name: 'Beef Patties',
    category: 'Protein',
    currentStock: 22,
    unit: 'kg',
    minStock: 15,
    maxStock: 60,
    levelPercent: 62,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'In Stock',
  },
  {
    id: 'INV-007',
    name: 'Fresh Tomatoes',
    category: 'Produce',
    currentStock: 9,
    unit: 'kg',
    minStock: 8,
    maxStock: 30,
    levelPercent: 30,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 7:00 AM',
    status: 'Low Stock',
  },
  {
    id: 'INV-008',
    name: 'Heavy Cream',
    category: 'Dairy',
    currentStock: 6,
    unit: 'L',
    minStock: 5,
    maxStock: 20,
    levelPercent: 42,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'In Stock',
  },
  {
    id: 'INV-009',
    name: 'Pasta (Dry)',
    category: 'Dry Goods',
    currentStock: 35,
    unit: 'kg',
    minStock: 15,
    maxStock: 80,
    levelPercent: 50,
    supplier: 'FreshDairy Co.',
    lastUpdated: '3 days ago',
    status: 'In Stock',
  },
  {
    id: 'INV-010',
    name: 'Eggs (Free Range)',
    category: 'Dairy',
    currentStock: 8,
    unit: 'doz',
    minStock: 10,
    maxStock: 40,
    levelPercent: 24,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 7:00 AM',
    status: 'Low Stock',
  },
  {
    id: 'INV-011',
    name: 'Romaine Lettuce',
    category: 'Produce',
    currentStock: 14,
    unit: 'heads',
    minStock: 10,
    maxStock: 40,
    levelPercent: 48,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 7:00 AM',
    status: 'In Stock',
  },
  {
    id: 'INV-012',
    name: 'Sparkling Water',
    category: 'Beverages',
    currentStock: 0,
    unit: 'btl',
    minStock: 24,
    maxStock: 120,
    levelPercent: 0,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Yesterday',
    status: 'Out of Stock',
  },
  {
    id: 'INV-013',
    name: 'Parmesan Cheese',
    category: 'Dairy',
    currentStock: 3,
    unit: 'kg',
    minStock: 5,
    maxStock: 20,
    levelPercent: 15,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'Critical',
  },
  {
    id: 'INV-014',
    name: 'Ground Coffee',
    category: 'Beverages',
    currentStock: 7,
    unit: 'kg',
    minStock: 5,
    maxStock: 25,
    levelPercent: 52,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'In Stock',
  },
  {
    id: 'INV-015',
    name: 'Bacon Strips',
    category: 'Protein',
    currentStock: 11,
    unit: 'kg',
    minStock: 8,
    maxStock: 35,
    levelPercent: 58,
    supplier: 'FreshDairy Co.',
    lastUpdated: 'Today 9:00 AM',
    status: 'In Stock',
  },
];
