import {
  LoyaltyMember,
  LoyaltyStats,
  TierDistributionItem,
  LTVLeaderboardItem,
} from './types';

export const initialLoyaltyStats: LoyaltyStats = {
  totalMembers: 7,
  vipCustomers: 2,
  totalLTV: 10660,
  birthdaysThisMonth: 3,
};

export const initialTierDistribution: TierDistributionItem[] = [
  {
    tier: 'VIP',
    membersCount: 2,
    percentage: 29,
    color: 'text-amber-500',
    barColor: 'bg-amber-500',
  },
  {
    tier: 'Gold',
    membersCount: 1,
    percentage: 14,
    color: 'text-amber-500',
    barColor: 'bg-amber-500',
  },
  {
    tier: 'Silver',
    membersCount: 2,
    percentage: 29,
    color: 'text-slate-400',
    barColor: 'bg-slate-400',
  },
  {
    tier: 'Bronze',
    membersCount: 2,
    percentage: 29,
    color: 'text-orange-400',
    barColor: 'bg-orange-400',
  },
];

export const initialLTVLeaderboard: LTVLeaderboardItem[] = [
  {
    rank: 1,
    initials: 'JC',
    name: 'James Carter',
    ltv: 3240,
    color: 'text-amber-500',
  },
  {
    rank: 2,
    initials: 'MP',
    name: 'Mia Patel',
    ltv: 2680,
    color: 'text-amber-500',
  },
  {
    rank: 3,
    initials: 'SJ',
    name: 'Sarah Johnson',
    ltv: 1840,
    color: 'text-amber-500',
  },
  {
    rank: 4,
    initials: 'AM',
    name: 'Ava Mitchell',
    ltv: 1120,
    color: 'text-slate-400',
  },
  {
    rank: 5,
    initials: 'MB',
    name: 'Michael Brown',
    ltv: 980,
    color: 'text-slate-400',
  },
];

export const initialLoyaltyMembers: LoyaltyMember[] = [
  {
    id: 'lm-1',
    name: 'James Carter',
    initials: 'JC',
    email: 'j.carter@email.com',
    tier: 'VIP',
    points: 3980,
    nextTierPoints: 5000,
    lifetimeValue: 3240,
    avgOrder: 48.36,
    visits: 67,
    birthday: 'Nov 14',
    isBirthdayToday: false,
    joinDate: 'Oct 2022',
    tags: ['👑 Loyal 2 Years', '🔥 Streak 14d', '📦 Bulk Buyer'],
    upsellSuggestions: [
      {
        id: 'u-1',
        name: 'Craft Beer',
        emoji: '🍺',
        reason: 'Always orders with dinner',
        probability: 82,
        applied: false,
      },
      {
        id: 'u-2',
        name: 'Side Salad',
        emoji: '🥗',
        reason: 'Health-conscious trend',
        probability: 55,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-2',
    name: 'Sarah Johnson',
    initials: 'SJ',
    email: 'sarah.j@email.com',
    tier: 'VIP',
    points: 3980,
    nextTierPoints: 5000,
    lifetimeValue: 1840,
    avgOrder: 43.8,
    visits: 42,
    birthday: 'Today!',
    isBirthdayToday: true,
    joinDate: 'Jan 2023',
    tags: ['🎂 Birthday Today', '⭐ High Tip Rate', '🍷 Wine Club'],
    suggestedBirthdayOffer: '🎂 Free dessert + 20% off entire bill',
    birthdayOfferSent: true,
    upsellSuggestions: [
      {
        id: 'u-3',
        name: 'Tiramisu Dessert',
        emoji: '🍰',
        reason: 'Birthday celebratory favorite',
        probability: 88,
        applied: false,
      },
      {
        id: 'u-4',
        name: 'Artisan Cappuccino',
        emoji: '☕',
        reason: 'Afternoon pairing habit',
        probability: 76,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-3',
    name: 'Mia Patel',
    initials: 'MP',
    email: 'mia.patel@email.com',
    tier: 'Gold',
    points: 2650,
    nextTierPoints: 5000,
    lifetimeValue: 2680,
    avgOrder: 52.1,
    visits: 51,
    birthday: 'Dec 02 (in 3 days)',
    isBirthdayToday: false,
    joinDate: 'Mar 2023',
    tags: ['⚡ Frequent Diner', '🎯 Near VIP'],
    suggestedBirthdayOffer: '🍾 Complimentary Champagne Flute with entree',
    birthdayOfferSent: false,
    upsellSuggestions: [
      {
        id: 'u-5',
        name: 'Truffle Fries',
        emoji: '🍟',
        reason: 'Highest repeat add-on',
        probability: 79,
        applied: false,
      },
      {
        id: 'u-6',
        name: 'Pinot Noir Glass',
        emoji: '🍷',
        reason: 'Evening dinner preference',
        probability: 64,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-4',
    name: 'Ava Mitchell',
    initials: 'AM',
    email: 'ava.m@email.com',
    tier: 'Silver',
    points: 1420,
    nextTierPoints: 2500,
    lifetimeValue: 1120,
    avgOrder: 38.5,
    visits: 29,
    birthday: 'Dec 18',
    isBirthdayToday: false,
    joinDate: 'Aug 2023',
    tags: ['☕ Morning Rush', '🥪 Lunch Regular'],
    suggestedBirthdayOffer: '🥐 Free Pastry with any Specialty Coffee',
    birthdayOfferSent: false,
    upsellSuggestions: [
      {
        id: 'u-7',
        name: 'Avocado Toast Upgrade',
        emoji: '🥑',
        reason: 'Pairs with morning coffee',
        probability: 71,
        applied: false,
      },
      {
        id: 'u-8',
        name: 'Matcha Latte',
        emoji: '🍵',
        reason: 'Health drink trend',
        probability: 58,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-5',
    name: 'Michael Brown',
    initials: 'MB',
    email: 'm.brown@email.com',
    tier: 'Silver',
    points: 1180,
    nextTierPoints: 2500,
    lifetimeValue: 980,
    avgOrder: 34.0,
    visits: 28,
    birthday: 'Jan 05',
    isBirthdayToday: false,
    joinDate: 'Sep 2023',
    tags: ['🍔 Burger Fan', '🥤 Soda Addict'],
    suggestedBirthdayOffer: '🍔 Free Gourmet Slider on birthday week',
    birthdayOfferSent: false,
    upsellSuggestions: [
      {
        id: 'u-9',
        name: 'Double Patty Upgrade',
        emoji: '🥩',
        reason: 'Upsize preference',
        probability: 85,
        applied: false,
      },
      {
        id: 'u-10',
        name: 'Loaded Cheesy Tots',
        emoji: '🧀',
        reason: 'High margin snack',
        probability: 62,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-6',
    name: 'Emma White',
    initials: 'EW',
    email: 'emma.w@email.com',
    tier: 'Bronze',
    points: 520,
    nextTierPoints: 1000,
    lifetimeValue: 460,
    avgOrder: 27.5,
    visits: 17,
    birthday: 'Dec 22',
    isBirthdayToday: false,
    joinDate: 'Nov 2023',
    tags: ['🌱 Vegetarian', '🍰 Sweet Tooth'],
    suggestedBirthdayOffer: '🍰 Free Slice of House Cheesecake',
    birthdayOfferSent: false,
    upsellSuggestions: [
      {
        id: 'u-11',
        name: 'Vegan Brownie',
        emoji: '🍫',
        reason: 'Sweet finish complement',
        probability: 68,
        applied: false,
      },
    ],
  },
  {
    id: 'lm-7',
    name: 'Noah Adams',
    initials: 'NA',
    email: 'noah.a@email.com',
    tier: 'Bronze',
    points: 380,
    nextTierPoints: 1000,
    lifetimeValue: 340,
    avgOrder: 24.3,
    visits: 14,
    birthday: 'Dec 29',
    isBirthdayToday: false,
    joinDate: 'Dec 2023',
    tags: ['📱 App User', '🚀 New Member'],
    suggestedBirthdayOffer: '☕ Free 16oz Cold Brew',
    birthdayOfferSent: false,
    upsellSuggestions: [
      {
        id: 'u-12',
        name: 'Cold Brew Upgrade',
        emoji: '🧊',
        reason: 'Fast morning grab',
        probability: 73,
        applied: false,
      },
    ],
  },
];
