import { PaymentItem } from './types';

export const INITIAL_TRANSACTIONS: PaymentItem[] = [
  {
    id: '#TX-8291',
    orderNumber: '#1048',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-04',
    server: 'Rahim Al-Amin',
    amount: 54.0,
    formattedAmount: '$ 54.00',
    method: 'Card',
    cardLast4: '4242',
    cardBrand: 'Visa',
    authCode: 'AUTH-82910',
    status: 'Completed',
    timestamp: 'Today, 12:40 PM',
    date: '2026-10-09',
    items: [
      { name: 'Prime Wagyu Ribeye (250g)', qty: 1, price: 38.0 },
      { name: 'House Truffle Herb Fries', qty: 1, price: 9.0 },
      { name: 'Sparkling San Pellegrino (750ml)', qty: 1, price: 7.0 },
    ],
  },
  {
    id: '#TX-8290',
    orderNumber: '#1047',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-02',
    server: 'Nusrat Jahan',
    amount: 54.0,
    formattedAmount: '$ 54.00',
    method: 'Card',
    cardLast4: '8821',
    cardBrand: 'Mastercard',
    authCode: 'AUTH-82901',
    status: 'Completed',
    timestamp: 'Today, 12:40 PM',
    date: '2026-10-09',
    items: [
      { name: 'Pan-Seared Chilean Sea Bass', qty: 1, price: 42.0 },
      { name: 'Organic Matcha Green Tea', qty: 2, price: 12.0 },
    ],
  },
  {
    id: '#TX-8289',
    orderNumber: '#1046',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-09',
    server: 'Tanvir Hossain',
    amount: 54.0,
    formattedAmount: '$ 54.00',
    method: 'Card',
    cardLast4: '1094',
    cardBrand: 'Amex',
    authCode: 'AUTH-82892',
    status: 'Completed',
    timestamp: 'Today, 12:40 PM',
    date: '2026-10-09',
    items: [
      { name: 'Handmade Truffle Tagliatelle', qty: 1, price: 34.0 },
      { name: 'Tiramisu Della Nonna', qty: 1, price: 12.0 },
      { name: 'Double Espresso', qty: 1, price: 8.0 },
    ],
  },
  {
    id: '#TX-8288',
    orderNumber: '#1045',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-01',
    server: 'Robert Geo',
    amount: 54.0,
    formattedAmount: '$ 54.00',
    method: 'Card',
    cardLast4: '3318',
    cardBrand: 'Visa',
    authCode: 'AUTH-82883',
    status: 'Completed',
    timestamp: 'Today, 12:40 PM',
    date: '2026-10-09',
    items: [
      { name: 'Wood-Fired Margherita D.O.P.', qty: 1, price: 24.0 },
      { name: 'Burrata Pugliese Salad', qty: 1, price: 18.0 },
      { name: 'Craft Ginger Ale', qty: 2, price: 12.0 },
    ],
  },
  {
    id: '#TX-8287',
    orderNumber: '#1044',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Bar Stool 03',
    server: 'Tanvir Hossain',
    amount: 210.0,
    formattedAmount: '$ 210.00',
    method: 'Cash',
    authCode: 'CASH-DRAWER-01',
    status: 'Completed',
    timestamp: 'Today, 11:55 AM',
    date: '2026-10-09',
    items: [
      { name: 'Chef Omakase Tasting Course', qty: 2, price: 180.0 },
      { name: 'Yuzu Botanical Spritz', qty: 2, price: 30.0 },
    ],
  },
  {
    id: '#TX-8286',
    orderNumber: '#1043',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-07',
    server: 'Rahim Al-Amin',
    amount: 45.0,
    formattedAmount: '$ 45.00',
    method: 'QR Pay',
    authCode: 'QRPAY-99014',
    status: 'Pending',
    timestamp: 'Today, 11:32 AM',
    date: '2026-10-09',
    items: [
      { name: 'Artisan Sourdough Garlic Bread', qty: 1, price: 14.0 },
      { name: 'Classic Carbonara Guanciale', qty: 1, price: 26.0 },
      { name: 'Acqua Panna Still (500ml)', qty: 1, price: 5.0 },
    ],
  },
  {
    id: '#TX-8285',
    orderNumber: '#1042',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-05',
    server: 'Nusrat Jahan',
    amount: 148.5,
    formattedAmount: '$ 148.50',
    method: 'Stripe',
    cardLast4: '5501',
    cardBrand: 'Visa',
    authCode: 'ch_3M4k9e2eZvKYlo2C1',
    status: 'Completed',
    timestamp: 'Today, 11:15 AM',
    date: '2026-10-09',
    items: [
      { name: 'Tomahawk Ribeye Steak (900g)', qty: 1, price: 120.0 },
      { name: 'Grilled Asparagus Hollandaise', qty: 1, price: 16.0 },
      { name: 'Mineral Sparkling Water', qty: 2, price: 12.5 },
    ],
  },
  {
    id: '#TX-8284',
    orderNumber: '#1041',
    restaurant: 'Tavonza Kitchen',
    branch: 'Gulshan Flagship',
    tableNumber: 'Table T-08',
    server: 'Robert Geo',
    amount: 72.0,
    formattedAmount: '$ 72.00',
    method: 'Card',
    cardLast4: '9924',
    cardBrand: 'Mastercard',
    authCode: 'AUTH-82844',
    status: 'Refunded',
    timestamp: 'Yesterday, 09:40 PM',
    date: '2026-10-08',
    items: [
      { name: 'Dry-Aged Beef Carpaccio', qty: 2, price: 44.0 },
      { name: 'House Berry Panna Cotta', qty: 2, price: 28.0 },
    ],
  },
];
