import {
  Layers,
  ShoppingBag,
  CheckCircle2,
  Users,
  Clock,
  Star,
  PlusCircle,
  PhoneCall,
  ArrowRightLeft,
  Receipt,
  Tag,
  UserCheck,
} from 'lucide-react';
import {
  WaiterKPI,
  PriorityTask,
  AssignedTable,
  LiveOrder,
  AIRecommendation,
  LiveAlert,
  GuestReview,
  CheckoutTable,
  QuickActionItem,
  GuestRequest,
} from './types';

export const mockWaiterProfile = {
  name: 'Michael Davis',
  role: 'Waiter',
  status: 'Shift Active',
  branch: 'Downtown Branch',
  group: 'Tavonza Group',
  shiftStart: '08:00 AM',
  shiftEnd: '04:00 PM',
  assignedTableCount: 8,
  activeOrderCount: 14,
};

export const mockKPIs: WaiterKPI[] = [
  {
    id: 'kpi-1',
    title: 'Assigned Tables',
    value: '08',
    subtitle: 'Currently Assigned',
    icon: Layers,
    iconColor: 'text-blue-500',
    iconBg: 'bg-blue-500/10',
    valueColor: 'text-white',
  },
  {
    id: 'kpi-2',
    title: 'Active Orders',
    value: '14',
    subtitle: 'Orders in Progress',
    icon: ShoppingBag,
    iconColor: 'text-amber-500',
    iconBg: 'bg-amber-500/10',
    valueColor: 'text-white',
  },
  {
    id: 'kpi-3',
    title: 'Orders Ready',
    value: '03',
    subtitle: 'Ready to Serve',
    icon: CheckCircle2,
    iconColor: 'text-emerald-500',
    iconBg: 'bg-emerald-500/10',
    valueColor: 'text-white',
  },
  {
    id: 'kpi-4',
    title: 'Guests Served',
    value: '38',
    subtitle: "Today's Guests",
    icon: Users,
    iconColor: 'text-purple-500',
    iconBg: 'bg-purple-500/10',
    valueColor: 'text-white',
  },
  {
    id: 'kpi-5',
    title: 'Avg. Service Time',
    value: '11 min',
    subtitle: 'Per Table',
    icon: Clock,
    iconColor: 'text-orange-500',
    iconBg: 'bg-orange-500/10',
    valueColor: 'text-white',
  },
  {
    id: 'kpi-6',
    title: 'Satisfaction',
    value: '4.9 / 5',
    subtitle: "Today's Rating",
    icon: Star,
    iconColor: 'text-amber-400',
    iconBg: 'bg-amber-500/10',
    valueColor: 'text-amber-400',
  },
];

export const mockPriorityTasks: PriorityTask[] = [
  {
    id: 'task-1',
    title: 'Serve Order #10582 → Table 12',
    table: 'Table 12',
    severity: 'high',
    dotColor: 'bg-red-500',
    completed: false,
  },
  {
    id: 'task-2',
    title: 'Table 5 requested assistance',
    table: 'Table 5',
    severity: 'medium',
    dotColor: 'bg-orange-500',
    completed: false,
  },
  {
    id: 'task-3',
    title: 'Deliver bill → Table 15',
    table: 'Table 15',
    severity: 'yellow',
    dotColor: 'bg-yellow-500',
    completed: false,
  },
  {
    id: 'task-4',
    title: 'Recommend desserts → Table 8',
    table: 'Table 8',
    severity: 'low',
    dotColor: 'bg-emerald-500',
    completed: false,
  },
];

export const mockAssignedTables: AssignedTable[] = [
  {
    id: 't-1',
    tableNumber: 'T-01',
    guests: 0,
    maxCapacity: 4,
    status: 'Available',
    waitMinutes: 18,
    notes: 'Cleaned & sanitized',
  },
  {
    id: 't-2',
    tableNumber: 'T-04',
    guests: 3,
    maxCapacity: 4,
    status: 'Dining',
    waitMinutes: 12,
    notes: 'Main course in prep',
  },
  {
    id: 't-3',
    tableNumber: 'T-05',
    guests: 2,
    maxCapacity: 2,
    status: 'Occupied',
    waitMinutes: 5,
    notes: 'Assistance requested',
  },
  {
    id: 't-4',
    tableNumber: 'T-08',
    guests: 4,
    maxCapacity: 6,
    status: 'Dining',
    waitMinutes: 24,
    notes: 'Main course completed',
  },
  {
    id: 't-5',
    tableNumber: 'T-12',
    guests: 2,
    maxCapacity: 4,
    status: 'Dining',
    waitMinutes: 18,
    notes: 'Food ready at kitchen',
  },
  {
    id: 't-6',
    tableNumber: 'T-15',
    guests: 5,
    maxCapacity: 6,
    status: 'Billing',
    waitMinutes: 8,
    notes: 'Bill requested - Birthday table',
  },
  {
    id: 't-7',
    tableNumber: 'T-18',
    guests: 2,
    maxCapacity: 2,
    status: 'Billing',
    waitMinutes: 4,
    notes: 'Split payment requested',
  },
  {
    id: 't-8',
    tableNumber: 'T-03',
    guests: 2,
    maxCapacity: 4,
    status: 'Dining',
    waitMinutes: 15,
    notes: 'VIP Guest - Mr. Henderson',
  },
];

export const mockLiveOrders: LiveOrder[] = [
  {
    id: 'ord-1',
    orderNumber: '#10582',
    tableNumber: 'T-12',
    items: ['Wagyu Truffle Burger', 'Parmesan Truffle Fries', 'Iced Hibiscus Tea'],
    status: 'Ready to Serve',
    statusColor: 'text-emerald-400',
    statusBg: 'bg-emerald-500/10 border-emerald-500/30',
    statusText: 'Ready to Serve',
    eta: 'Ready',
    timeAgo: '2m ago',
  },
  {
    id: 'ord-2',
    orderNumber: '#10583',
    tableNumber: 'T-04',
    items: ['Grilled Salmon Risotto', 'Caesar Salad', 'Sparkling Water'],
    status: 'Preparing',
    statusColor: 'text-amber-400',
    statusBg: 'bg-amber-500/10 border-amber-500/30',
    statusText: 'Preparing',
    eta: '18min',
    timeAgo: '6m ago',
  },
  {
    id: 'ord-3',
    orderNumber: '#10584',
    tableNumber: 'T-08',
    items: ['Artisan Margherita Pizza', 'Burrata Salad', 'Aperol Spritz x2'],
    status: 'Ready to Serve',
    statusColor: 'text-emerald-400',
    statusBg: 'bg-emerald-500/10 border-emerald-500/30',
    statusText: 'Ready to Serve',
    eta: 'Ready',
    timeAgo: '1m ago',
  },
  {
    id: 'ord-4',
    orderNumber: '#10585',
    tableNumber: 'T-12',
    items: ['Warm Chocolate Lava Cake', 'Espresso Macchiato'],
    status: 'Served',
    statusColor: 'text-zinc-400',
    statusBg: 'bg-zinc-500/10 border-zinc-700/50',
    statusText: 'Served',
    eta: 'Done',
    timeAgo: '14m ago',
  },
  {
    id: 'ord-5',
    orderNumber: '#10586',
    tableNumber: 'T-02',
    items: ['Dry-Aged Ribeye Steak', 'Roasted Asparagus', 'Cabernet Sauvignon'],
    status: 'New Order',
    statusColor: 'text-blue-400',
    statusBg: 'bg-blue-500/15 border-blue-500/30',
    statusText: 'New Order',
    eta: '18min',
    timeAgo: 'Just now',
  },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: 'rec-1',
    category: 'Upsell',
    categoryColor: 'text-purple-400',
    categoryBg: 'bg-purple-500/10 border-purple-500/30',
    title: 'Table 8 finished main course',
    description: 'Offer Chocolate Lava Cake.',
    targetTable: 'Table 8',
    iconType: 'cake',
  },
  {
    id: 'rec-2',
    category: 'Beverage',
    categoryColor: 'text-blue-400',
    categoryBg: 'bg-blue-500/10 border-blue-500/30',
    title: 'Table 5 usually orders iced tea',
    description: 'Suggest iced tea after lunch.',
    targetTable: 'Table 5',
    iconType: 'glass',
  },
  {
    id: 'rec-3',
    category: 'VIP Guest',
    categoryColor: 'text-amber-400',
    categoryBg: 'bg-amber-500/10 border-amber-500/30',
    title: 'Table 3 — returning VIP',
    description: 'Greet by name, priority service.',
    targetTable: 'Table 3',
    iconType: 'star',
  },
  {
    id: 'rec-4',
    category: 'Birthday',
    categoryColor: 'text-emerald-400',
    categoryBg: 'bg-emerald-500/10 border-emerald-500/30',
    title: 'Table 15 celebrating birthday',
    description: 'Offer complimentary dessert.',
    targetTable: 'Table 15',
    iconType: 'sparkles',
  },
];

export const mockLiveAlerts: LiveAlert[] = [
  {
    id: 'alt-1',
    message: 'Table 12 waiting for food for 18 minutes.',
    severity: 'red',
    dotColor: 'bg-red-500',
    timeAgo: '2m ago',
  },
  {
    id: 'alt-2',
    message: 'Order #10582 is ready for pickup.',
    severity: 'yellow',
    dotColor: 'bg-yellow-500',
    timeAgo: '4m ago',
  },
  {
    id: 'alt-3',
    message: 'Table 15 requested the bill.',
    severity: 'green',
    dotColor: 'bg-emerald-500',
    timeAgo: '6m ago',
  },
  {
    id: 'alt-4',
    message: 'Customer at Table 5 pressed assistance.',
    severity: 'orange',
    dotColor: 'bg-orange-500',
    timeAgo: '8m ago',
  },
];

export const mockGuestReviews: GuestReview[] = [
  {
    id: 'rev-1',
    guestName: 'Sarah Johnson',
    rating: 5,
    comment: '"Fast payment process and friendly staff."',
    timeAgo: '20m ago',
  },
  {
    id: 'rev-2',
    guestName: 'David Miller',
    rating: 5,
    comment: '"Michael gave fantastic wine pairing recommendations!"',
    timeAgo: '45m ago',
  },
];

export const mockCheckoutTables: CheckoutTable[] = [
  {
    id: 'chk-1',
    tableNumber: 'T-15',
    amount: 82.40,
    status: 'Ready',
    statusColor: 'text-emerald-400',
    statusBg: 'bg-emerald-500/10 border-emerald-500/30',
    guestName: 'Sarah Johnson',
    itemCount: 4,
  },
  {
    id: 'chk-2',
    tableNumber: 'T-18',
    amount: 82.40,
    status: 'Waiting',
    statusColor: 'text-yellow-400',
    statusBg: 'bg-yellow-500/10 border-yellow-500/30',
    guestName: 'Robert Lang',
    itemCount: 3,
  },
  {
    id: 'chk-3',
    tableNumber: 'T-07',
    amount: 114.50,
    status: 'Ready',
    statusColor: 'text-emerald-400',
    statusBg: 'bg-emerald-500/10 border-emerald-500/30',
    guestName: 'Emma Watson',
    itemCount: 6,
  },
];

export const mockQuickActions: QuickActionItem[] = [
  {
    id: 'qa-1',
    title: 'Create Manual Order',
    description: 'Add items directly to table',
    icon: PlusCircle,
  },
  {
    id: 'qa-2',
    title: 'Call Host / Kitchen',
    description: 'Direct intercom message',
    icon: PhoneCall,
  },
  {
    id: 'qa-3',
    title: 'Table Transfer',
    description: 'Move guests to new table',
    icon: ArrowRightLeft,
  },
  {
    id: 'qa-4',
    title: 'Split / Print Bill',
    description: 'Generate receipt copy',
    icon: Receipt,
  },
  {
    id: 'qa-5',
    title: 'Apply Discount',
    description: 'Staff or promo discount',
    icon: Tag,
  },
  {
    id: 'qa-6',
    title: 'Request Shift Relief',
    description: 'Break or handover request',
    icon: UserCheck,
  },
];

export const mockGuestRequests: GuestRequest[] = [
  {
    id: 'gr-1',
    tableNumber: 'Table 05',
    type: 'Water Refill',
    status: 'Pending',
    timeAgo: '3m ago',
    notes: 'Still water with lemon',
  },
  {
    id: 'gr-2',
    tableNumber: 'Table 15',
    type: 'Bill Request',
    status: 'In Progress',
    timeAgo: '6m ago',
    notes: 'Card payment machine requested',
  },
  {
    id: 'gr-3',
    tableNumber: 'Table 08',
    type: 'Extra Cutlery',
    status: 'Pending',
    timeAgo: '9m ago',
    notes: '2 extra dessert spoons',
  },
  {
    id: 'gr-4',
    tableNumber: 'Table 12',
    type: 'Waiter Call',
    status: 'Resolved',
    timeAgo: '15m ago',
    notes: 'Checked on steak temperature',
  },
];
