import {
  LoyaltyKPIs,
  LoyaltyTier,
  LoyaltyReward,
  LoyaltyActivity,
} from './types';

export const INITIAL_LOYALTY_KPIS: LoyaltyKPIs = {
  totalMembers: '1,132',
  pointsIssued: '284,600',
  pointsRedeemed: '118,240',
  programRevenue: '+18.4%',
};

export const INITIAL_LOYALTY_TIERS: LoyaltyTier[] = [
  {
    id: 'tier-bronze',
    name: 'Bronze',
    pointsRange: '0 – 499 pts',
    colorTheme: 'text-yellow-500',
    borderTheme: 'outline-yellow-500/30 border-yellow-500/30',
    iconBg: 'bg-orange-200/20 text-amber-600',
    textColor: 'text-amber-500',
    metricLabel: 'Entry Level Tier',
    metricValue: '0 – 499 pts',
    perks: ['5% discount on orders', 'Birthday reward'],
  },
  {
    id: 'tier-silver',
    name: 'Silver',
    pointsRange: '500 – 1,499 pts',
    colorTheme: 'text-slate-300',
    borderTheme: 'outline-blue-500/30 border-blue-500/30',
    iconBg: 'bg-blue-200/20 text-slate-300',
    textColor: 'text-slate-300',
    metricLabel: 'Avg Order Value',
    metricValue: '$64.50',
    growth: '↑ 6.3%',
    perks: ['10% discount on orders', 'Free specialty coffee on visit'],
  },
  {
    id: 'tier-gold',
    name: 'Gold',
    pointsRange: '1,500 – 4,999 pts',
    colorTheme: 'text-yellow-400',
    borderTheme: 'outline-yellow-500/30 border-yellow-500/30',
    iconBg: 'bg-orange-200/20 text-amber-500',
    textColor: 'text-yellow-400',
    metricLabel: 'Total Revenue',
    metricValue: '$42,800',
    growth: '↑ 12.8%',
    perks: ['15% discount on orders', 'Priority table reservations'],
  },
  {
    id: 'tier-platinum',
    name: 'Platinum',
    pointsRange: '5,000+ pts',
    colorTheme: 'text-purple-400',
    borderTheme: 'outline-purple-500/30 border-purple-500/30',
    iconBg: 'bg-purple-400/20 text-purple-400',
    textColor: 'text-purple-400',
    metricLabel: 'Top Category',
    metricValue: 'VIP Dining',
    growth: 'Burgers',
    perks: ['20% discount on orders', "Dedicated VIP host & Chef's tasting"],
  },
];

export const INITIAL_LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'rew-1',
    icon: '🍰',
    name: 'Free Dessert',
    pointsCost: 200,
    claimedCount: 48,
    category: 'Dessert',
    description: 'Any signature dessert slice or gelato cup from our bakery menu.',
  },
  {
    id: 'rew-2',
    icon: '🏷️',
    name: '10% Off Order',
    pointsCost: 300,
    claimedCount: 124,
    category: 'Discount',
    description: 'Applied instantly to the entire check on your next visit.',
  },
  {
    id: 'rew-3',
    icon: '☕',
    name: 'Free Specialty Coffee',
    pointsCost: 150,
    claimedCount: 89,
    category: 'Beverage',
    description: 'Artisan cappuccino, latte, or cold brew prepared by our barista.',
  },
  {
    id: 'rew-4',
    icon: '🍟',
    name: 'Free Appetizer',
    pointsCost: 250,
    claimedCount: 62,
    category: 'Appetizer',
    description: 'Choice of truffle fries, crispy calamari, or loaded nachos.',
  },
  {
    id: 'rew-5',
    icon: '🥂',
    name: 'VIP Table for 2',
    pointsCost: 800,
    claimedCount: 12,
    category: 'Experience',
    description: 'Priority prime window seating with complimentary champagne welcome.',
  },
  {
    id: 'rew-6',
    icon: '🍽️',
    name: "Chef's Tasting Menu",
    pointsCost: 1500,
    claimedCount: 4,
    category: 'VIP Dining',
    description: '5-course exclusive seasonal tasting pairing with head sommelier.',
  },
];

export const INITIAL_LOYALTY_ACTIVITIES: LoyaltyActivity[] = [
  {
    id: 'act-1',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    userName: 'Ava Martinez',
    action: 'Redeemed 500 points',
    timeAgo: '2 min ago',
    pointsChange: -500,
  },
  {
    id: 'act-2',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    userName: 'James Clark',
    action: 'Earned points on order #10521',
    timeAgo: '15 min ago',
    pointsChange: 93,
  },
  {
    id: 'act-3',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    userName: 'Olivia Brown',
    action: 'Upgraded to Platinum tier',
    timeAgo: '1h ago',
    badge: '👑',
    isUpgrade: true,
  },
  {
    id: 'act-4',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    userName: 'Emma Wilson',
    action: 'Earned points on order #10518',
    timeAgo: '2h ago',
    pointsChange: 79,
  },
  {
    id: 'act-5',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    userName: 'Isabella Harris',
    action: 'Redeemed free dessert',
    timeAgo: '3h ago',
    pointsChange: -200,
  },
  {
    id: 'act-6',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    userName: 'Lucas Scott',
    action: 'Earned points on order #10514',
    timeAgo: '4h ago',
    pointsChange: 142,
  },
];
