import { RestaurantBranch, Manager, StaffMember, DaySchedule } from './types';

export const DEFAULT_OPERATING_HOURS: DaySchedule[] = [
  { day: 'Monday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Tuesday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Wednesday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Thursday', isOpen: true, openTime: '09:00 AM', closeTime: '11:00 PM' },
  { day: 'Friday', isOpen: true, openTime: '09:00 AM', closeTime: '11:59 PM' },
  { day: 'Saturday', isOpen: true, openTime: '10:00 AM', closeTime: '11:59 PM' },
  { day: 'Sunday', isOpen: true, openTime: '10:00 AM', closeTime: '10:00 PM' },
];

export const MOCK_MANAGERS: Manager[] = [
  {
    id: 'mgr-1',
    name: 'Sarah Ahmed',
    role: 'Restaurant Manager',
    email: 'sarah@tavonza.com',
    avatar: 'SA',
    phone: '+880 1712-345678',
  },
  {
    id: 'mgr-2',
    name: 'Alex Rivera',
    role: 'General Manager',
    email: 'alex.rivera@tavonza.com',
    avatar: 'AR',
    phone: '+880 1819-456789',
  },
  {
    id: 'mgr-3',
    name: 'Michael Chen',
    role: 'Operations Manager',
    email: 'm.chen@tavonza.com',
    avatar: 'MC',
    phone: '+880 1912-789012',
  },
  {
    id: 'mgr-4',
    name: 'Sofia Patel',
    role: 'Floor Manager',
    email: 'sofia.patel@tavonza.com',
    avatar: 'SP',
    phone: '+880 1611-234567',
  },
  {
    id: 'mgr-5',
    name: 'Rahim Chowdhury',
    role: 'Senior Branch Manager',
    email: 'rahim.c@tavonza.com',
    avatar: 'RC',
    phone: '+880 1515-998877',
  },
];

export const MOCK_STAFF_POOL: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'John Smith',
    role: 'Cashier',
    avatar: 'JS',
    email: 'john.smith@tavonza.com',
    shift: 'Morning (08:00 - 16:00)',
  },
  {
    id: 'staff-2',
    name: 'Emma Watson',
    role: 'Waiter',
    avatar: 'EW',
    email: 'emma.w@tavonza.com',
    shift: 'Evening (16:00 - 00:00)',
  },
  {
    id: 'staff-3',
    name: 'David Lee',
    role: 'Kitchen Staff',
    avatar: 'DL',
    email: 'david.lee@tavonza.com',
    shift: 'Morning (07:30 - 15:30)',
  },
  {
    id: 'staff-4',
    name: 'Carlos Gomez',
    role: 'Bartender',
    avatar: 'CG',
    email: 'carlos.g@tavonza.com',
    shift: 'Night (18:00 - 02:00)',
  },
  {
    id: 'staff-5',
    name: 'Aisha Rahman',
    role: 'Assistant Manager',
    avatar: 'AR',
    email: 'aisha.r@tavonza.com',
    shift: 'Full Day (09:00 - 18:00)',
  },
  {
    id: 'staff-6',
    name: 'Tariq Hassan',
    role: 'Delivery Staff',
    avatar: 'TH',
    email: 'tariq.h@tavonza.com',
    shift: 'Afternoon (12:00 - 20:00)',
  },
  {
    id: 'staff-7',
    name: 'Liam Neeson',
    role: 'Waiter',
    avatar: 'LN',
    email: 'liam.n@tavonza.com',
    shift: 'Evening (16:00 - 00:00)',
  },
  {
    id: 'staff-8',
    name: 'Elena Rostova',
    role: 'Kitchen Staff',
    avatar: 'ER',
    email: 'elena.r@tavonza.com',
    shift: 'Morning (07:30 - 15:30)',
  },
  {
    id: 'staff-9',
    name: 'Hassan Ali',
    role: 'Cashier',
    avatar: 'HA',
    email: 'hassan.a@tavonza.com',
    shift: 'Evening (15:00 - 23:00)',
  },
  {
    id: 'staff-10',
    name: 'Nadia Karim',
    role: 'Bartender',
    avatar: 'NK',
    email: 'nadia.k@tavonza.com',
    shift: 'Night (18:00 - 02:00)',
  },
];

export const INITIAL_RESTAURANTS: RestaurantBranch[] = [
  {
    id: 'rest-1',
    name: 'Tavonza Downtown',
    type: 'Restaurant',
    address: 'Road 27, House 42',
    city: 'Dhanmondi',
    country: 'Dhaka',
    postalCode: '1209',
    phone: '+880 2-9661234',
    email: 'downtown@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[0],
    staffCount: 12,
    assignedStaff: MOCK_STAFF_POOL.slice(0, 5),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Dine-In', 'Takeaway', 'Delivery'],
    branchesCount: 3,
    revenue: '$42,850/mo',
    rating: 4.9,
    tablesCount: 28,
  },
  {
    id: 'rest-2',
    name: 'Tavonza Gulshan Bistro',
    type: 'Restaurant',
    address: 'Avenue 5, Gulshan 2',
    city: 'Gulshan',
    country: 'Dhaka',
    postalCode: '1212',
    phone: '+880 2-8819876',
    email: 'gulshan@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[1],
    staffCount: 16,
    assignedStaff: MOCK_STAFF_POOL.slice(2, 7),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Dine-In', 'Takeaway', 'Delivery', 'Catering'],
    branchesCount: 2,
    revenue: '$68,400/mo',
    rating: 4.8,
    tablesCount: 36,
  },
  {
    id: 'rest-3',
    name: 'Tavonza Waterfront Club',
    type: 'Bar',
    address: 'Lake Drive, Banani 11',
    city: 'Banani',
    country: 'Dhaka',
    postalCode: '1213',
    phone: '+880 2-9884567',
    email: 'waterfront@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[2],
    staffCount: 14,
    assignedStaff: MOCK_STAFF_POOL.slice(1, 6),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Dine-In', 'Bar', 'Catering'],
    branchesCount: 1,
    revenue: '$54,200/mo',
    rating: 4.7,
    tablesCount: 22,
  },
  {
    id: 'rest-4',
    name: 'Tavonza Café & Bakery',
    type: 'Café',
    address: 'Sector 4, Uttara Model Town',
    city: 'Uttara',
    country: 'Dhaka',
    postalCode: '1230',
    phone: '+880 2-7912345',
    email: 'uttara@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[3],
    staffCount: 9,
    assignedStaff: MOCK_STAFF_POOL.slice(3, 8),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Dine-In', 'Takeaway', 'Bakery'],
    branchesCount: 1,
    revenue: '$29,100/mo',
    rating: 4.9,
    tablesCount: 18,
  },
  {
    id: 'rest-5',
    name: 'Tavonza Express Airport',
    type: 'Fast Food',
    address: 'Terminal 2 Concourse',
    city: 'Kurmitola',
    country: 'Dhaka',
    postalCode: '1229',
    phone: '+880 2-8901234',
    email: 'airport@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[4],
    staffCount: 11,
    assignedStaff: MOCK_STAFF_POOL.slice(0, 4),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Takeaway', 'Fast Food'],
    branchesCount: 1,
    revenue: '$38,700/mo',
    rating: 4.6,
    tablesCount: 14,
  },
  {
    id: 'rest-6',
    name: 'Tavonza Rooftop Lounge',
    type: 'Restaurant',
    address: 'Mirpur DOHS Central',
    city: 'Mirpur',
    country: 'Dhaka',
    postalCode: '1216',
    phone: '+880 2-9012345',
    email: 'rooftop@tavonza.com',
    status: 'Closed',
    manager: MOCK_MANAGERS[0],
    staffCount: 10,
    assignedStaff: MOCK_STAFF_POOL.slice(4, 9),
    operatingHours: DEFAULT_OPERATING_HOURS,
    services: ['Dine-In', 'Catering'],
    branchesCount: 1,
    revenue: '$31,500/mo',
    rating: 4.8,
    tablesCount: 24,
  },
];

export const INITIAL_BRANCHES: Record<string, import('./types').BranchItem[]> = {
  'rest-1': [
    {
      id: 'branch-1',
      restaurantId: 'rest-1',
      restaurantName: 'Tavonza Downtown',
      name: 'Tavonza Uttara',
      address: 'Sector 3, Jashimuddin Avenue',
      city: 'Uttara',
      country: 'Dhaka',
      postalCode: '1230',
      phone: '+880 2-8911223',
      email: 'uttara.branch@tavonza.com',
      status: 'Open',
      manager: {
        id: 'bmgr-1',
        name: 'Arif Hossain',
        role: 'Branch Manager',
        email: 'arif@tavonza.com',
        avatar: 'AH',
        phone: '+880 1711-223344',
      },
      staffCount: 7,
      assignedStaff: MOCK_STAFF_POOL.slice(0, 4),
      revenue: '$22,400/mo',
    },
    {
      id: 'branch-2',
      restaurantId: 'rest-1',
      restaurantName: 'Tavonza Downtown',
      name: 'Tavonza Banani',
      address: 'Block E, Road 11',
      city: 'Banani',
      country: 'Dhaka',
      postalCode: '1213',
      phone: '+880 2-9844556',
      email: 'banani.branch@tavonza.com',
      status: 'Closed',
      manager: {
        id: 'bmgr-2',
        name: 'Arif Hossain',
        role: 'Branch Manager',
        email: 'arif@tavonza.com',
        avatar: 'AH',
        phone: '+880 1711-223344',
      },
      staffCount: 7,
      assignedStaff: MOCK_STAFF_POOL.slice(3, 7),
      revenue: '$18,900/mo',
    },
    {
      id: 'branch-3',
      restaurantId: 'rest-1',
      restaurantName: 'Tavonza Downtown',
      name: 'Tavonza Mirpur',
      address: 'Mirpur 10 Circle',
      city: 'Mirpur',
      country: 'Dhaka',
      postalCode: '1216',
      phone: '+880 2-9011223',
      email: 'mirpur.branch@tavonza.com',
      status: 'Open',
      manager: {
        id: 'bmgr-3',
        name: 'Arif Hossain',
        role: 'Branch Manager',
        email: 'arif@tavonza.com',
        avatar: 'AH',
        phone: '+880 1711-223344',
      },
      staffCount: 7,
      assignedStaff: MOCK_STAFF_POOL.slice(1, 5),
      revenue: '$24,100/mo',
    },
  ],
};

