import { CashierOrder, OrderStatus } from './types';

export const ORDER_STATUS_TABS: OrderStatus[] = [
  'All',
  'Paid',
  'Pending',
  'Preparing',
  'Ready',
  'Cancelled',
];

export const INITIAL_ORDERS: CashierOrder[] = [
  {
    id: 'ord-1',
    orderNumber: '#10590',
    table: 'T-08',
    customer: 'James Carter',
    itemsCount: 4,
    method: 'Visa Card',
    status: 'Preparing',
    total: 52.40,
    time: '12:45pm',
  },
  {
    id: 'ord-2',
    orderNumber: '#10589',
    table: 'T-04',
    customer: 'Marcus Vance',
    itemsCount: 3,
    method: 'Apple Pay',
    status: 'Paid',
    total: 44.50,
    time: '12:38pm',
  },
  {
    id: 'ord-3',
    orderNumber: '#10588',
    table: 'T-02',
    customer: 'Elena Rostova',
    itemsCount: 2,
    method: 'Mastercard',
    status: 'Ready',
    total: 36.00,
    time: '12:30pm',
  },
  {
    id: 'ord-4',
    orderNumber: '#10587',
    table: 'T-07',
    customer: 'Liam Chen',
    itemsCount: 5,
    method: 'Cash',
    status: 'Preparing',
    total: 78.20,
    time: '12:25pm',
  },
  {
    id: 'ord-5',
    orderNumber: '#10586',
    table: 'T-01',
    customer: 'Sarah Jenkins',
    itemsCount: 2,
    method: 'Visa Card',
    status: 'Paid',
    total: 29.80,
    time: '12:18pm',
  },
  {
    id: 'ord-6',
    orderNumber: '#10585',
    table: 'T-12',
    customer: 'Noah Adams',
    itemsCount: 5,
    method: 'Visa',
    status: 'Pending',
    total: 68.40,
    time: '12:10pm',
  },
  {
    id: 'ord-7',
    orderNumber: '#10584',
    table: 'T-09',
    customer: 'David Miller',
    itemsCount: 1,
    method: 'Amex Card',
    status: 'Paid',
    total: 18.50,
    time: '12:02pm',
  },
  {
    id: 'ord-8',
    orderNumber: '#10583',
    table: 'T-03',
    customer: 'Olivia Taylor',
    itemsCount: 3,
    method: 'QR / Digital',
    status: 'Cancelled',
    total: 41.20,
    time: '11:55am',
  },
];
