import { DocumentCategory, DocumentItem } from './types';

export const DOCUMENT_CATEGORIES: DocumentCategory[] = [
  'Compliance',
  'Legal',
  'Operations',
  'HR',
  'Contracts',
  'Finance',
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'Health & Safety Certificate 2025',
    category: 'Compliance',
    size: '2.4 MB',
    uploadedBy: 'John Carter',
    date: 'Jul 10, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Jul 10, 2026',
  },
  {
    id: 'doc-2',
    title: 'Business License Q3 2025',
    category: 'Legal',
    size: '1.1 MB',
    uploadedBy: 'John Carter',
    date: 'Jul 5, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Dec 31, 2025',
  },
  {
    id: 'doc-3',
    title: 'Food Hygiene Audit Report',
    category: 'Compliance',
    size: '3.8 MB',
    uploadedBy: 'Sarah Jenkins',
    date: 'Jun 28, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Jun 28, 2026',
  },
  {
    id: 'doc-4',
    title: 'Commercial Lease Agreement',
    category: 'Legal',
    size: '5.2 MB',
    uploadedBy: 'Elena Vance',
    date: 'Jun 15, 2025',
    status: 'Expiring Soon',
    fileType: 'PDF',
    expiryDate: 'Aug 15, 2025',
  },
  {
    id: 'doc-5',
    title: 'Supplier Master Contract - AgriFarm',
    category: 'Contracts',
    size: '1.8 MB',
    uploadedBy: 'Marcus Vance',
    date: 'May 30, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'May 30, 2026',
  },
  {
    id: 'doc-6',
    title: 'Employment Agreement - Head Chef',
    category: 'HR',
    size: '850 KB',
    uploadedBy: 'Sarah Jenkins',
    date: 'May 14, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'May 14, 2026',
  },
  {
    id: 'doc-7',
    title: 'Annual Fire Inspection Certificate',
    category: 'Operations',
    size: '2.1 MB',
    uploadedBy: 'John Carter',
    date: 'Apr 20, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Apr 20, 2026',
  },
  {
    id: 'doc-8',
    title: 'Liquor License Renewal 2025',
    category: 'Legal',
    size: '1.4 MB',
    uploadedBy: 'Elena Vance',
    date: 'Apr 10, 2025',
    status: 'Expiring Soon',
    fileType: 'PDF',
    expiryDate: 'Aug 30, 2025',
  },
  {
    id: 'doc-9',
    title: 'Kitchen Standard Operating Procedures',
    category: 'Operations',
    size: '4.6 MB',
    uploadedBy: 'David Ross',
    date: 'Mar 25, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Mar 25, 2027',
  },
  {
    id: 'doc-10',
    title: 'Quarterly Financial Audit Q2',
    category: 'Finance',
    size: '6.7 MB',
    uploadedBy: 'Michael Chang',
    date: 'Mar 12, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Mar 12, 2026',
  },
  {
    id: 'doc-11',
    title: 'Staff Code of Conduct & Workplace Safety',
    category: 'HR',
    size: '1.9 MB',
    uploadedBy: 'Sarah Jenkins',
    date: 'Feb 28, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Feb 28, 2026',
  },
  {
    id: 'doc-12',
    title: 'Beverage Vendor Agreement - Vineyards Co.',
    category: 'Contracts',
    size: '2.3 MB',
    uploadedBy: 'Marcus Vance',
    date: 'Feb 15, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Feb 15, 2026',
  },
  {
    id: 'doc-13',
    title: 'Insurance Policy - Property & Liability',
    category: 'Compliance',
    size: '4.1 MB',
    uploadedBy: 'John Carter',
    date: 'Jan 30, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Jan 30, 2026',
  },
  {
    id: 'doc-14',
    title: 'HVAC Maintenance & Ventilation Report',
    category: 'Operations',
    size: '1.6 MB',
    uploadedBy: 'David Ross',
    date: 'Jan 18, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Jan 18, 2026',
  },
  {
    id: 'doc-15',
    title: 'Annual Corporate Tax Filing 2024',
    category: 'Finance',
    size: '8.4 MB',
    uploadedBy: 'Michael Chang',
    date: 'Jan 05, 2025',
    status: 'Valid',
    fileType: 'PDF',
    expiryDate: 'Jan 05, 2026',
  },
];
