import { Recipe } from './types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'REC-001',
    name: 'Classic Burger',
    category: 'Burgers',
    stepsCount: 6,
    rating: 4.8,
    prepTimeMinutes: 12,
    servings: 1,
    foodCost: 4.2,
    salePrice: 18.9,
    marginPercent: 77,
    imageUrl:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '200g Beef Patty',
      '1 Brioche Bun',
      'Lettuce',
      'Tomato',
      'Pickles',
      '30ml House Sauce',
    ],
    instructions: [
      'Preheat flat-top grill to 400°F (200°C).',
      'Season 200g beef patty with sea salt and black pepper.',
      'Sear patty for 3 minutes per side until medium.',
      'Toast brioche bun lightly with butter.',
      'Layer base bun with house sauce, lettuce, and sliced tomato.',
      'Top with patty, pickles, and top bun. Serve warm.',
    ],
  },
  {
    id: 'REC-002',
    name: 'Truffle Mushroom Pizza',
    category: 'Pizza',
    stepsCount: 8,
    rating: 4.9,
    prepTimeMinutes: 15,
    servings: 2,
    foodCost: 5.8,
    salePrice: 24.5,
    marginPercent: 76,
    imageUrl:
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '250g Sourdough Pizza Dough',
      '120g Mozzarella Cheese',
      '80g Portobello Mushrooms',
      '15ml White Truffle Oil',
      'Fresh Thyme',
      'Parmesan Shavings',
    ],
    instructions: [
      'Stretch pizza dough to 12 inches.',
      'Spread thin mozzarella base.',
      'Arrange sliced mushrooms evenly.',
      'Bake at 500°F in stone oven for 7 minutes.',
      'Drizzle white truffle oil and finish with fresh thyme and parmesan.',
    ],
  },
  {
    id: 'REC-003',
    name: 'Authentic Carbonara',
    category: 'Pasta',
    stepsCount: 5,
    rating: 4.7,
    prepTimeMinutes: 14,
    servings: 1,
    foodCost: 3.9,
    salePrice: 19.5,
    marginPercent: 80,
    imageUrl:
      'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '150g Rigatoni Pasta',
      '60g Guanciale Strips',
      '2 Fresh Egg Yolks',
      '40g Pecorino Romano',
      'Coarse Black Pepper',
    ],
    instructions: [
      'Boil pasta in salted water until al dente.',
      'Crisp guanciale in a skillet without extra oil.',
      'Whisk egg yolks and grated Pecorino with black pepper.',
      'Toss pasta into guanciale pan off heat.',
      'Stir in egg cheese emulsion with pasta water to create silky glaze.',
    ],
  },
  {
    id: 'REC-004',
    name: 'Mediterranean Caesar',
    category: 'Salads',
    stepsCount: 4,
    rating: 4.6,
    prepTimeMinutes: 8,
    servings: 1,
    foodCost: 2.8,
    salePrice: 14.0,
    marginPercent: 80,
    imageUrl:
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '1 Head Romaine Lettuce',
      '40g Garlic Herb Croutons',
      '30g Shaved Parmesan',
      '40ml House Caesar Dressing',
      'Anchovy Filets (Optional)',
    ],
    instructions: [
      'Wash and crisp fresh romaine lettuce leaves.',
      'Chop into bite-sized pieces.',
      'Toss with creamy house Caesar dressing.',
      'Garnish with golden croutons and shaved parmesan.',
    ],
  },
  {
    id: 'REC-005',
    name: 'Double Smash Cheeseburger',
    category: 'Burgers',
    stepsCount: 7,
    rating: 4.9,
    prepTimeMinutes: 10,
    servings: 1,
    foodCost: 4.5,
    salePrice: 20.5,
    marginPercent: 78,
    imageUrl:
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '2x 100g Angus Beef Patties',
      '2 Slices American Cheddar',
      'Grilled Onions',
      'Potato Bun',
      'Secret Smash Sauce',
    ],
    instructions: [
      'Smash thin on screaming hot griddle for maximum crust.',
      'Season aggressively and flip after 90 seconds.',
      'Melt cheese over patties and stack.',
      'Toast potato bun with butter and assemble with sauce and onions.',
    ],
  },
  {
    id: 'REC-006',
    name: 'Artisan Margherita Pizza',
    category: 'Pizza',
    stepsCount: 6,
    rating: 4.8,
    prepTimeMinutes: 12,
    servings: 2,
    foodCost: 3.4,
    salePrice: 17.5,
    marginPercent: 81,
    imageUrl:
      'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      '250g Neapolitan Dough',
      '90ml San Marzano Tomato Sauce',
      '100g Fresh Buffalo Mozzarella',
      'Fresh Basil Leaves',
      'Extra Virgin Olive Oil',
    ],
    instructions: [
      'Hand stretch dough keeping an airy cornicione crust.',
      'Ladle crushed San Marzano tomato sauce.',
      'Tear buffalo mozzarella chunks across pie.',
      'Bake at 550°F for 90 seconds in wood fire oven.',
      'Top with fresh basil and EVOO drizzle.',
    ],
  },
  {
    id: 'REC-007',
    name: 'Classic Italian Tiramisu',
    category: 'Desserts',
    stepsCount: 5,
    rating: 4.9,
    prepTimeMinutes: 20,
    servings: 2,
    foodCost: 3.1,
    salePrice: 12.5,
    marginPercent: 75,
    imageUrl:
      'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      'Savoiardi Ladyfingers',
      '250g Mascarpone Cheese',
      'Fresh Espresso',
      'Marsala Wine',
      'Valrhona Cocoa Powder',
    ],
    instructions: [
      'Whip mascarpone with egg yolks and sugar until velvety.',
      'Dip ladyfingers quickly in espresso and Marsala mixture.',
      'Layer ladyfingers and cream alternately in glassware.',
      'Chill for 4 hours.',
      'Dust generously with Dutch cocoa powder before serving.',
    ],
  },
  {
    id: 'REC-008',
    name: 'Wild Berry Cheesecake',
    category: 'Desserts',
    stepsCount: 6,
    rating: 4.8,
    prepTimeMinutes: 25,
    servings: 1,
    foodCost: 2.9,
    salePrice: 11.9,
    marginPercent: 76,
    imageUrl:
      'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    ingredients: [
      'Graham Cracker Crust',
      'Philadelphia Cream Cheese',
      'Organic Raspberries & Blueberries',
      'Lemon Zest',
      'Mint Leaves',
    ],
    instructions: [
      'Prepare buttered biscuit base.',
      'Fold smooth cream cheese with vanilla and lemon zest.',
      'Set in mold and refrigerate overnight.',
      'Top with warm wild berry compote and fresh mint.',
    ],
  },
];
