import { Employee, EmployeesKPIs } from './types';

export const INITIAL_EMPLOYEES_KPIS: EmployeesKPIs = {
  totalStaff: 8,
  onShift: 7,
  avgRating: 4.6,
  tablesServed: 103,
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Jake R.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Head Waiter',
    status: 'On Shift',
    shiftHours: '10:00 AM – 6:00 PM',
    shiftType: 'Morning',
    rating: 4.9,
    tablesToday: 34,
    accuracy: 98,
    phone: '+1 (555) 012-3456',
    email: 'jake.r@tavonza.com',
    bio: 'Top performer this quarter. Handles VIP tables.',
    notes: 'Certified sommelier. Prefers Section A dining room.',
    hireDate: 'Mar 2023',
    salary: 3800,
  },
  {
    id: 'emp-2',
    name: 'Marco V.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Chef',
    status: 'On Duty',
    shiftHours: '8:00 AM – 4:00 PM',
    shiftType: 'Morning',
    rating: 4.9,
    tablesToday: 34,
    accuracy: 82,
    phone: '+1 (555) 678-9012',
    email: 'marco.v@tavonza.com',
    bio: 'Head chef. Oversees all kitchen operations.',
    notes: 'Culinary Institute grad. Manages dinner line prep.',
    hireDate: 'Jan 2022',
    salary: 5200,
  },
  {
    id: 'emp-3',
    name: 'Remy D.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Bartender',
    status: 'Off Duty',
    shiftHours: '4:00 PM – 12:00 AM',
    shiftType: 'Night',
    rating: 4.9,
    tablesToday: 34,
    accuracy: 94,
    phone: '+1 (555) 345-6789',
    email: 'remy.d@tavonza.com',
    bio: 'Cocktail specialist with 5 years craft mixology experience.',
    notes: 'Designed signature cocktail menu for summer.',
    hireDate: 'Aug 2023',
    salary: 3600,
  },
  {
    id: 'emp-4',
    name: 'Sophia L.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Hostess',
    status: 'On Shift',
    shiftHours: '11:00 AM – 7:00 PM',
    shiftType: 'Morning',
    rating: 4.8,
    tablesToday: 42,
    accuracy: 99,
    phone: '+1 (555) 234-5678',
    email: 'sophia.l@tavonza.com',
    bio: 'Front desk coordinator managing guest seating and reservations.',
    notes: 'Fluent in English and Spanish. Excellent guest rapport.',
    hireDate: 'Nov 2023',
    salary: 3200,
  },
  {
    id: 'emp-5',
    name: 'Carlos M.',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'Waiter',
    status: 'On Shift',
    shiftHours: '12:00 PM – 8:00 PM',
    shiftType: 'Evening',
    rating: 4.7,
    tablesToday: 28,
    accuracy: 95,
    phone: '+1 (555) 456-7890',
    email: 'carlos.m@tavonza.com',
    bio: 'Speedy table turnover and attentive beverage service.',
    notes: 'Handles outdoor patio during peak dinner rush.',
    hireDate: 'Feb 2024',
    salary: 3100,
  },
  {
    id: 'emp-6',
    name: 'Elena S.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'Barista',
    status: 'On Duty',
    shiftHours: '7:00 AM – 3:00 PM',
    shiftType: 'Morning',
    rating: 4.9,
    tablesToday: 38,
    accuracy: 96,
    phone: '+1 (555) 567-8901',
    email: 'elena.s@tavonza.com',
    bio: 'Artisan coffee specialist and dessert station manager.',
    notes: 'Certified latte art instructor.',
    hireDate: 'May 2023',
    salary: 3300,
  },
  {
    id: 'emp-7',
    name: 'David K.',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    role: 'Chef',
    status: 'On Shift',
    shiftHours: '3:00 PM – 11:00 PM',
    shiftType: 'Evening',
    rating: 4.6,
    tablesToday: 26,
    accuracy: 91,
    phone: '+1 (555) 789-0123',
    email: 'david.k@tavonza.com',
    bio: 'Sous chef leading grilling and hot appetizers station.',
    notes: 'Specializes in steak cuts and pasta dishes.',
    hireDate: 'Oct 2022',
    salary: 4400,
  },
  {
    id: 'emp-8',
    name: 'Aisha B.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Manager',
    status: 'On Shift',
    shiftHours: '9:00 AM – 5:00 PM',
    shiftType: 'Morning',
    rating: 5.0,
    tablesToday: 15,
    accuracy: 100,
    phone: '+1 (555) 890-1234',
    email: 'aisha.b@tavonza.com',
    bio: 'Floor general manager ensuring high quality hospitality standards.',
    notes: 'Supervises staff schedule, inventory, and supplier deliveries.',
    hireDate: 'Jan 2021',
    salary: 6200,
  },
];
