import { CardMember, CardTier, CardTierInfo } from './types';

export const CARD_TIERS: CardTier[] = ['Platinum', 'Gold', 'Silver', 'Bronze'];

export const INITIAL_CARD_MEMBERS: CardMember[] = [
  {
    id: 'mem-1',
    cardId: 'TCV-0001',
    name: 'Emma Wilson',
    email: 'emma@email.com',
    tier: 'Platinum',
    points: 12480,
    totalSpend: 1296,
    visits: 48,
    lastVisit: 'Today',
    joined: 'Jun 2026',
    status: 'Active',
  },
  {
    id: 'mem-2',
    cardId: 'TCV-0002',
    name: 'James Williams',
    email: 'james@email.com',
    tier: 'Gold',
    points: 1480,
    totalSpend: 3496,
    visits: 32,
    lastVisit: 'Today',
    joined: 'May 2026',
    status: 'Active',
  },
  {
    id: 'mem-3',
    cardId: 'TCV-0003',
    name: 'Sarah Miller',
    email: 'sarah@email.com',
    tier: 'Gold',
    points: 7820,
    totalSpend: 9486,
    visits: 28,
    lastVisit: 'Yesterday',
    joined: 'Apr 2024',
    status: 'Active',
  },
  {
    id: 'mem-4',
    cardId: 'TCV-0004',
    name: 'David Chen',
    email: 'david@email.com',
    tier: 'Silver',
    points: 6340,
    totalSpend: 1496,
    visits: 50,
    lastVisit: '2 days ago',
    joined: 'Apr 2024',
    status: 'Active',
  },
  {
    id: 'mem-5',
    cardId: 'TCV-0005',
    name: 'Olivia Martinez',
    email: 'olivia@email.com',
    tier: 'Silver',
    points: 3240,
    totalSpend: 2496,
    visits: 65,
    lastVisit: '3 days ago',
    joined: 'Apr 2024',
    status: 'Active',
  },
  {
    id: 'mem-6',
    cardId: 'TCV-0006',
    name: 'Noah Thompson',
    email: 'noah@email.com',
    tier: 'Silver',
    points: 2880,
    totalSpend: 2996,
    visits: 48,
    lastVisit: '1 week ago',
    joined: 'Apr 2024',
    status: 'Active',
  },
  {
    id: 'mem-7',
    cardId: 'TCV-0007',
    name: 'Ava Johnson',
    email: 'ava@email.com',
    tier: 'Bronze',
    points: 2120,
    totalSpend: 1496,
    visits: 24,
    lastVisit: '2 weeks ago',
    joined: 'Aug 2025',
    status: 'Active',
  },
  {
    id: 'mem-8',
    cardId: 'TCV-0008',
    name: 'Benjamin Wilson',
    email: 'ben@email.com',
    tier: 'Bronze',
    points: 980,
    totalSpend: 2496,
    visits: 52,
    lastVisit: 'Yesterday',
    joined: 'May 2025',
    status: 'Inactive',
  },
  {
    id: 'mem-9',
    cardId: 'TCV-0009',
    name: 'Charlotte Lee',
    email: 'charlie@email.com',
    tier: 'Platinum',
    points: 740,
    totalSpend: 1496,
    visits: 60,
    lastVisit: '1 month ago',
    joined: 'Apr 2025',
    status: 'Active',
  },
  {
    id: 'mem-10',
    cardId: 'TCV-0010',
    name: 'William Brown',
    email: 'will@email.com',
    tier: 'Bronze',
    points: 15200,
    totalSpend: 3496,
    visits: 24,
    lastVisit: 'Today',
    joined: 'Mar 2025',
    status: 'Inactive',
  },
  {
    id: 'mem-11',
    cardId: 'TCV-0011',
    name: 'Grace Kim',
    email: 'grace@email.com',
    tier: 'Gold',
    points: 520,
    totalSpend: 4456,
    visits: 43,
    lastVisit: '4 days ago',
    joined: 'Feb 2025',
    status: 'Active',
  },
  {
    id: 'mem-12',
    cardId: 'TCV-0012',
    name: 'Ryan Park',
    email: 'ryan@email.com',
    tier: 'Silver',
    points: 2540,
    totalSpend: 1493,
    visits: 25,
    lastVisit: '12:05 PM',
    joined: 'Feb 2025',
    status: 'Active',
  },
  {
    id: 'mem-13',
    cardId: 'TCV-0013',
    name: 'Benjamin Wilson',
    email: 'ben@email.com',
    tier: 'Platinum',
    points: 12480,
    totalSpend: 3492,
    visits: 13,
    lastVisit: '11:55 AM',
    joined: 'Feb 2025',
    status: 'Active',
  },
  {
    id: 'mem-14',
    cardId: 'TCV-0014',
    name: 'Noah Thompson',
    email: 'noah@email.com',
    tier: 'Platinum',
    points: 2540,
    totalSpend: 4426,
    visits: 45,
    lastVisit: '11:40 AM',
    joined: 'Jan 2025',
    status: 'Active',
  },
];

export const TIER_DEFINITIONS: CardTierInfo[] = [
  {
    tier: 'Platinum',
    criteria: '10,000+ pts',
    count: 2,
    color: 'text-purple-400',
  },
  {
    tier: 'Gold',
    criteria: '5,000–9,999 pts',
    count: 3,
    color: 'text-yellow-400',
  },
  {
    tier: 'Silver',
    criteria: '1,000–4,999 pts',
    count: 4,
    color: 'text-slate-300',
  },
  {
    tier: 'Bronze',
    criteria: '0–999 pts',
    count: 3,
    color: 'text-orange-400',
  },
];
