import { Customer, CustomersKPIs } from './types';

export const INITIAL_CUSTOMERS_KPIS: CustomersKPIs = {
  totalCustomers: 10,
  vipMembers: 4,
  avgSpend: 248,
  visitsToday: 1290,
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Emma Wilson',
    email: 'emma@email.com',
    phone: '+1 (555) 100-1122',
    segment: 'VIP',
    visits: 48,
    totalSpent: 1296,
    rating: 4.9,
    lastVisit: 'Today',
    memberSince: 'Jan 2023',
    notes: 'Prefers quiet booth near window. Loves truffle pasta.',
  },
  {
    id: 'cust-2',
    name: 'James Williams',
    email: 'james@email.com',
    phone: '+1 (555) 234-5678',
    segment: 'VIP',
    visits: 38,
    totalSpent: 3496,
    rating: 4.9,
    lastVisit: 'Today',
    memberSince: 'Mar 2023',
    notes: 'Frequent dinner guest with business partners.',
  },
  {
    id: 'cust-3',
    name: 'Sarah Miller',
    email: 'sarah@email.com',
    phone: '+1 (555) 345-6789',
    segment: 'Regular',
    visits: 22,
    totalSpent: 9486,
    rating: 4.9,
    lastVisit: 'Yesterday',
    memberSince: 'Jun 2023',
    notes: 'Allergic to peanuts. Organic wine enthusiast.',
  },
  {
    id: 'cust-4',
    name: 'David Chen',
    email: 'david@email.com',
    phone: '+1 (555) 456-7890',
    segment: 'Regular',
    visits: 15,
    totalSpent: 1496,
    rating: 4.9,
    lastVisit: '2 days ago',
    memberSince: 'Sep 2023',
    notes: 'Weekend brunch regular with family.',
  },
  {
    id: 'cust-5',
    name: 'Olivia Martinez',
    email: 'olivia@email.com',
    phone: '+1 (555) 567-8901',
    segment: 'New',
    visits: 4,
    totalSpent: 2496,
    rating: 4.9,
    lastVisit: '3 days ago',
    memberSince: 'Aug 2026',
    notes: 'Visited during restaurant opening promotion.',
  },
  {
    id: 'cust-6',
    name: 'Noah Thompson',
    email: 'noah@email.com',
    phone: '+1 (555) 678-9012',
    segment: 'VIP',
    visits: 52,
    totalSpent: 2996,
    rating: 4.9,
    lastVisit: '1 week ago',
    memberSince: 'Nov 2022',
    notes: 'Top tier VIP guest. Reserve Table 12.',
  },
  {
    id: 'cust-7',
    name: 'Ava Johnson',
    email: 'ava@email.com',
    phone: '+1 (555) 789-0123',
    segment: 'Regular',
    visits: 18,
    totalSpent: 1496,
    rating: 4.9,
    lastVisit: '2 weeks ago',
    memberSince: 'Dec 2023',
    notes: 'Prefers dairy-free options.',
  },
  {
    id: 'cust-8',
    name: 'Benjamin Wilson',
    email: 'ben@email.com',
    phone: '+1 (555) 890-1234',
    segment: 'New',
    visits: 2,
    totalSpent: 2496,
    rating: 4.9,
    lastVisit: 'Yesterday',
    memberSince: 'Aug 2026',
    notes: 'Ordered craft cocktails and chef special.',
  },
  {
    id: 'cust-9',
    name: 'Charlotte Lee',
    email: 'charlie@email.com',
    phone: '+1 (555) 901-2345',
    segment: 'Regular',
    visits: 28,
    totalSpent: 1496,
    rating: 4.9,
    lastVisit: '1 month ago',
    memberSince: 'Apr 2023',
    notes: 'Corporate catering contact.',
  },
  {
    id: 'cust-10',
    name: 'William Brown',
    email: 'will@email.com',
    phone: '+1 (555) 012-3456',
    segment: 'New',
    visits: 41,
    totalSpent: 3496,
    rating: 4.9,
    lastVisit: 'Today',
    memberSince: 'Feb 2024',
    notes: 'Enjoys patio seating.',
  },
  {
    id: 'cust-11',
    name: 'Grace Kim',
    email: 'grace@email.com',
    phone: '+1 (555) 123-4567',
    segment: 'VIP',
    visits: 24,
    totalSpent: 4456,
    rating: 4.9,
    lastVisit: '4 days ago',
    memberSince: 'May 2023',
    notes: 'Birthday celebration regular.',
  },
  {
    id: 'cust-12',
    name: 'Ryan Park',
    email: 'ryan@email.com',
    phone: '+1 (555) 234-5670',
    segment: 'New',
    visits: 54,
    totalSpent: 1493,
    rating: 4.9,
    lastVisit: '12:05 PM',
    memberSince: 'Jul 2024',
    notes: 'Lunch express orders.',
  },
  {
    id: 'cust-13',
    name: 'James Chen',
    email: 'james.c@email.com',
    phone: '+1 (555) 555-2002',
    segment: 'VIP',
    visits: 36,
    totalSpent: 1820,
    rating: 4.8,
    lastVisit: 'Yesterday',
    memberSince: 'Mar 2023',
    notes: 'Sommelier club member. Loves reserve vintages.',
  },
  {
    id: 'cust-14',
    name: 'Lucas Scott',
    email: 'lucas@email.com',
    phone: '+1 (555) 432-1098',
    segment: 'New',
    visits: 25,
    totalSpent: 4426,
    rating: 4.9,
    lastVisit: '11:40 AM',
    memberSince: 'Aug 2026',
    notes: 'Late dinner reservations.',
  },
  {
    id: 'cust-15',
    name: 'Sophia Davis',
    email: 'sophia.d@email.com',
    phone: '+1 (555) 876-5432',
    segment: 'VIP',
    visits: 63,
    totalSpent: 3492,
    rating: 4.9,
    lastVisit: '11:55 AM',
    memberSince: 'Oct 2022',
    notes: 'VIP dining club president.',
  },
];
