import { Supplier } from './types';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'SUP-001',
    name: 'Fresh Farm Co.',
    contactPerson: 'Mark Stevens',
    category: 'Produce',
    phone: '+1 555-2201',
    email: 'mark@freshfarm.com',
    location: 'California, USA',
    reliabilityPercent: 98,
    lastOrder: '2 days ago',
    nextDelivery: 'Tomorrow',
    productsCount: 24,
    status: 'Active',
    products: [
      { name: 'Organic Romaine Lettuce (Box)', defaultQty: 10, unitPrice: 5.5 },
      { name: 'Heirloom Vine Tomatoes (kg)', defaultQty: 5, unitPrice: 12.0 },
      { name: 'Baby Spinach (kg)', defaultQty: 4, unitPrice: 8.5 },
      { name: 'Red Bell Peppers (Crate)', defaultQty: 2, unitPrice: 15.0 },
    ],
    orderHistory: [
      {
        id: 'ORD-8821',
        date: 'Jul 12, 2025',
        itemsCount: 8,
        totalAmount: 1240,
        status: 'Delivered',
      },
      {
        id: 'ORD-8714',
        date: 'Jun 28, 2025',
        itemsCount: 6,
        totalAmount: 980,
        status: 'Delivered',
      },
      {
        id: 'ORD-8603',
        date: 'Jun 14, 2025',
        itemsCount: 10,
        totalAmount: 1560,
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'SUP-002',
    name: 'Gourmet Dairy Ltd.',
    contactPerson: 'Mark Stevens',
    category: 'Dairy',
    phone: '+1 555-2202',
    email: 'orders@gourmetdairy.com',
    location: 'Wisconsin, USA',
    reliabilityPercent: 95,
    lastOrder: 'Today',
    nextDelivery: 'Friday',
    productsCount: 18,
    status: 'Active',
    products: [
      { name: 'Fresh Whole Milk (Crate)', defaultQty: 12, unitPrice: 4.5 },
      { name: 'Heavy Whipping Cream (L)', defaultQty: 8, unitPrice: 6.2 },
      { name: 'Buffalo Mozzarella (kg)', defaultQty: 15, unitPrice: 14.0 },
    ],
    orderHistory: [
      {
        id: 'ORD-8820',
        date: 'Jul 10, 2025',
        itemsCount: 5,
        totalAmount: 850,
        status: 'Delivered',
      },
      {
        id: 'ORD-8702',
        date: 'Jun 24, 2025',
        itemsCount: 7,
        totalAmount: 1120,
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'SUP-003',
    name: 'Ocean Catch Seafood',
    contactPerson: 'Mark Stevens',
    category: 'Seafood',
    phone: '+1 555-2203',
    email: 'sales@oceancatch.com',
    location: 'Maine, USA',
    reliabilityPercent: 91,
    lastOrder: '3 days ago',
    nextDelivery: 'Next week',
    productsCount: 15,
    status: 'Active',
    products: [
      { name: 'Atlantic Salmon Fillets (kg)', defaultQty: 10, unitPrice: 22.0 },
      { name: 'Tiger Prawns (kg)', defaultQty: 6, unitPrice: 18.5 },
      { name: 'Sea Bass Fillets (kg)', defaultQty: 8, unitPrice: 26.0 },
    ],
    orderHistory: [
      {
        id: 'ORD-8815',
        date: 'Jul 08, 2025',
        itemsCount: 4,
        totalAmount: 1420,
        status: 'Delivered',
      },
      {
        id: 'ORD-8690',
        date: 'Jun 20, 2025',
        itemsCount: 6,
        totalAmount: 1890,
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'SUP-004',
    name: 'Prime Meats Inc.',
    contactPerson: 'Mark Stevens',
    category: 'Meat',
    phone: '+1 555-2204',
    email: 'support@primemeats.com',
    location: 'Texas, USA',
    reliabilityPercent: 99,
    lastOrder: 'Yesterday',
    nextDelivery: 'Thursday',
    productsCount: 22,
    status: 'Active',
    products: [
      { name: 'Angus Beef Patties (kg)', defaultQty: 20, unitPrice: 14.5 },
      { name: 'Smoked Bacon Strips (kg)', defaultQty: 10, unitPrice: 11.0 },
      { name: 'Organic Chicken Breast (kg)', defaultQty: 15, unitPrice: 9.8 },
    ],
    orderHistory: [
      {
        id: 'ORD-8821',
        date: 'Jul 12, 2025',
        itemsCount: 8,
        totalAmount: 1240,
        status: 'Delivered',
      },
      {
        id: 'ORD-8714',
        date: 'Jun 28, 2025',
        itemsCount: 6,
        totalAmount: 980,
        status: 'Delivered',
      },
      {
        id: 'ORD-8603',
        date: 'Jun 14, 2025',
        itemsCount: 10,
        totalAmount: 1560,
        status: 'Delivered',
      },
      {
        id: 'ORD-8491',
        date: 'May 30, 2025',
        itemsCount: 7,
        totalAmount: 1120,
        status: 'Delivered',
      },
      {
        id: 'ORD-8380',
        date: 'May 16, 2025',
        itemsCount: 9,
        totalAmount: 1380,
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'SUP-005',
    name: 'Spice World',
    contactPerson: 'Mark Stevens',
    category: 'Dry Goods',
    phone: '+1 555-2205',
    email: 'info@spiceworld.com',
    location: 'Illinois, USA',
    reliabilityPercent: 82,
    lastOrder: '2 weeks ago',
    nextDelivery: '__',
    productsCount: 16,
    status: 'Inactive',
    products: [
      { name: 'Black Peppercorn (kg)', defaultQty: 5, unitPrice: 8.0 },
      { name: 'Sea Salt Flakes (kg)', defaultQty: 10, unitPrice: 4.5 },
      { name: 'Italian Herbs Blend (kg)', defaultQty: 3, unitPrice: 12.0 },
    ],
    orderHistory: [
      {
        id: 'ORD-8510',
        date: 'May 10, 2025',
        itemsCount: 3,
        totalAmount: 420,
        status: 'Delivered',
      },
    ],
  },
  {
    id: 'SUP-006',
    name: 'Beverage Plus',
    contactPerson: 'Mark Stevens',
    category: 'Beverages',
    phone: '+1 555-2206',
    email: 'orders@beverageplus.com',
    location: 'New York, USA',
    reliabilityPercent: 94,
    lastOrder: '4 days ago',
    nextDelivery: 'Next Monday',
    productsCount: 22,
    status: 'Active',
    products: [
      { name: 'Craft IPA Cans (Case of 24)', defaultQty: 8, unitPrice: 36.0 },
      { name: 'Sparkling Water 750ml (Case of 12)', defaultQty: 15, unitPrice: 18.0 },
      { name: 'Italian Espresso Beans (kg)', defaultQty: 10, unitPrice: 24.0 },
    ],
    orderHistory: [
      {
        id: 'ORD-8801',
        date: 'Jul 04, 2025',
        itemsCount: 8,
        totalAmount: 1180,
        status: 'Delivered',
      },
      {
        id: 'ORD-8650',
        date: 'Jun 18, 2025',
        itemsCount: 5,
        totalAmount: 760,
        status: 'Delivered',
      },
    ],
  },
];
