import { RestaurantBranch, Manager, StaffMember, DaySchedule, BranchItem, MenuItem, SubBranch } from './types';

export const DEFAULT_OPERATING_HOURS: DaySchedule[] = [
  { day: 'Monday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Tuesday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Wednesday', isOpen: true, openTime: '09:00 AM', closeTime: '10:00 PM' },
  { day: 'Thursday', isOpen: true, openTime: '09:00 AM', closeTime: '11:00 PM' },
  { day: 'Friday', isOpen: true, openTime: '09:00 AM', closeTime: '11:59 PM' },
  { day: 'Saturday', isOpen: true, openTime: '10:00 AM', closeTime: '11:59 PM' },
  { day: 'Sunday', isOpen: true, openTime: '10:00 AM', closeTime: '10:00 PM' },
];

export const MOCK_MANAGERS: Manager[] = [
  {
    id: 'mgr-1',
    name: 'Sarah Ahmed',
    role: 'Restaurant Manager',
    email: 'sarah@tavonza.com',
    avatar: 'SA',
    phone: '+880 1712-345678',
  },
  {
    id: 'mgr-2',
    name: 'Rafi Islam',
    role: 'General Manager',
    email: 'rafi@tavonza.com',
    avatar: 'RI',
    phone: '+880 1819-456789',
  },
  {
    id: 'mgr-3',
    name: 'Nadia Chowdhury',
    role: 'Operations Manager',
    email: 'nadia@tavonza.com',
    avatar: 'NC',
    phone: '+880 1912-789012',
  },
];

export const MOCK_STAFF_POOL: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'John Smith',
    role: 'Cashier',
    avatar: 'JS',
    email: 'john.smith@tavonza.com',
    shift: 'Morning (08:00 - 16:00)',
    days: ['Mon', 'Wed', 'Fri'],
    status: 'Active',
  },
  {
    id: 'staff-2',
    name: 'Michael Lee',
    role: 'Waiter',
    avatar: 'ML',
    email: 'michael.lee@tavonza.com',
    shift: 'Evening (16:00 - 00:00)',
    days: ['Tue', 'Thu', 'Sat'],
    status: 'Active',
  },
  {
    id: 'staff-3',
    name: 'David Khan',
    role: 'Kitchen Staff',
    avatar: 'DK',
    email: 'david.khan@tavonza.com',
    shift: 'Morning (07:30 - 15:30)',
    days: ['Mon', 'Tue', 'Thu'],
    status: 'Active',
  },
  {
    id: 'staff-4',
    name: 'Emma Wilson',
    role: 'Bartender',
    avatar: 'EW',
    email: 'emma.w@tavonza.com',
    shift: 'Night (18:00 - 02:00)',
    days: ['Fri', 'Sat', 'Sun'],
    status: 'On Leave',
  },
  {
    id: 'staff-5',
    name: 'Priya Sen',
    role: 'Delivery Staff',
    avatar: 'PS',
    email: 'priya.s@tavonza.com',
    shift: 'Full Day (09:00 - 18:00)',
    days: ['Wed', 'Sat'],
    status: 'Active',
  },
];

export const INITIAL_RESTAURANTS: RestaurantBranch[] = [
  {
    id: 'rest-1',
    codeId: 'REST-0001',
    name: 'Tavonza Downtown',
    type: 'Restaurant',
    address: 'Dhanmondi, Dhaka',
    city: 'Dhanmondi',
    country: 'Dhaka',
    postalCode: '1209',
    phone: '+880 2-9661234',
    email: 'downtown@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[0],
    staffCount: 12,
    branchesCount: 2,
    revenue: '৳4,28,500/mo',
    rating: 4.9,
    tablesCount: 28,
    services: ['Dine-In', 'Delivery', 'Pickup', 'QR Ordering'],
    operatingHours: DEFAULT_OPERATING_HOURS,
    detailStats: {
      thisMonthRevenue: '৳4,28,500',
      thisMonthRevenueChange: '+18%',
      totalOrders: '1,284',
      totalOrdersChange: '+9%',
      avgDailyRevenue: '৳13,820',
      avgDailyRevenueChange: '-3%',
    },
    branchesList: [
      {
        id: 'br-1',
        name: 'Tavonza Uttara',
        location: 'Uttara, Dhaka · 7 staff',
        staffCount: 7,
        status: 'Open',
        manager: 'Arif Hossain',
        address: 'Sector 4, Uttara, Dhaka',
        phone: '+880 1711-112233',
      },
      {
        id: 'br-2',
        name: 'Tavonza Mirpur',
        location: 'Mirpur, Dhaka · 5 staff',
        staffCount: 5,
        status: 'Closed',
        manager: 'Priya Sen',
        address: 'Section 10, Mirpur, Dhaka',
        phone: '+880 1722-223344',
      },
    ],
    assignedStaff: [
      {
        id: 'st-1',
        name: 'John Smith',
        role: 'Cashier',
        avatar: 'JS',
        restaurantName: 'Tavonza Downtown',
        days: ['Mon', 'Wed', 'Fri'],
        status: 'Active',
      },
      {
        id: 'st-2',
        name: 'Michael Lee',
        role: 'Waiter',
        avatar: 'ML',
        restaurantName: 'Tavonza Downtown',
        days: ['Tue', 'Thu', 'Sat'],
        status: 'Active',
      },
      {
        id: 'st-3',
        name: 'Emma Wilson',
        role: 'Bartender',
        avatar: 'EW',
        restaurantName: 'Tavonza Downtown',
        days: ['Fri', 'Sat', 'Sun'],
        status: 'On Leave',
      },
      {
        id: 'st-4',
        name: 'David Khan',
        role: 'Kitchen Staff',
        avatar: 'DK',
        restaurantName: 'Tavonza Downtown',
        days: ['Mon', 'Tue', 'Thu'],
        status: 'Active',
      },
      {
        id: 'st-5',
        name: 'Priya Sen',
        role: 'Delivery Staff',
        avatar: 'PS',
        restaurantName: 'Tavonza Downtown',
        days: ['Wed', 'Sat'],
        status: 'Active',
      },
    ],
    menuItems: [
      {
        id: 'menu-1',
        name: 'Grilled Chicken',
        category: 'Main Course',
        price: '৳480',
        status: 'Available',
      },
      {
        id: 'menu-2',
        name: 'Beef Burger',
        category: 'Fast Food',
        price: '৳350',
        status: 'Available',
      },
      {
        id: 'menu-3',
        name: 'Caesar Salad',
        category: 'Starters',
        price: '৳220',
        status: 'Available',
      },
      {
        id: 'menu-4',
        name: 'Pasta Carbonara',
        category: 'Main Course',
        price: '৳420',
        status: 'Out of Stock',
      },
      {
        id: 'menu-5',
        name: 'Chocolate Lava Cake',
        category: 'Desserts',
        price: '৳180',
        status: 'Available',
      },
    ],
  },
  {
    id: 'rest-2',
    codeId: 'REST-0002',
    name: 'Café Bloom',
    type: 'Café',
    address: 'Gulshan, Dhaka',
    city: 'Gulshan',
    country: 'Dhaka',
    postalCode: '1212',
    phone: '+880 2-8819876',
    email: 'bloom@tavonza.com',
    status: 'Open',
    manager: MOCK_MANAGERS[1],
    staffCount: 8,
    branchesCount: 1,
    revenue: '৳2,45,200/mo',
    rating: 4.8,
    tablesCount: 18,
    services: ['Dine-In', 'Delivery', 'Pickup'],
    operatingHours: DEFAULT_OPERATING_HOURS,
    detailStats: {
      thisMonthRevenue: '৳2,45,200',
      thisMonthRevenueChange: '+14%',
      totalOrders: '890',
      totalOrdersChange: '+11%',
      avgDailyRevenue: '৳8,150',
      avgDailyRevenueChange: '+4%',
    },
    branchesList: [
      {
        id: 'br-bloom-1',
        name: 'Café Bloom Banani',
        location: 'Banani, Dhaka · 4 staff',
        staffCount: 4,
        status: 'Open',
        manager: 'Tanvir Ahmed',
        address: 'Road 11, Banani, Dhaka',
        phone: '+880 1811-334455',
      },
    ],
    assignedStaff: [
      {
        id: 'st-b1',
        name: 'Rafi Islam',
        role: 'Manager',
        avatar: 'RI',
        restaurantName: 'Café Bloom',
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        status: 'Active',
      },
      {
        id: 'st-b2',
        name: 'Sadia Zaman',
        role: 'Barista',
        avatar: 'SZ',
        restaurantName: 'Café Bloom',
        days: ['Mon', 'Wed', 'Fri'],
        status: 'Active',
      },
      {
        id: 'st-b3',
        name: 'Tariq Mahmud',
        role: 'Cashier',
        avatar: 'TM',
        restaurantName: 'Café Bloom',
        days: ['Tue', 'Thu', 'Sat'],
        status: 'Active',
      },
    ],
    menuItems: [
      {
        id: 'menu-b1',
        name: 'Spanish Latte',
        category: 'Beverages',
        price: '৳280',
        status: 'Available',
      },
      {
        id: 'menu-b2',
        name: 'Croissant Supreme',
        category: 'Bakery',
        price: '৳190',
        status: 'Available',
      },
      {
        id: 'menu-b3',
        name: 'Avocado Toast',
        category: 'Brunch',
        price: '৳320',
        status: 'Available',
      },
    ],
  },
  {
    id: 'rest-3',
    codeId: 'REST-0003',
    name: 'The Barrel Bar',
    type: 'Bar',
    address: 'Banani, Dhaka',
    city: 'Banani',
    country: 'Dhaka',
    postalCode: '1213',
    phone: '+880 2-9884567',
    email: 'barrel@tavonza.com',
    status: 'Closed',
    manager: MOCK_MANAGERS[2],
    staffCount: 15,
    branchesCount: 0,
    revenue: '৳3,10,000/mo',
    rating: 4.7,
    tablesCount: 22,
    services: ['Dine-In', 'Bar', 'Private Events'],
    operatingHours: DEFAULT_OPERATING_HOURS,
    detailStats: {
      thisMonthRevenue: '৳3,10,000',
      thisMonthRevenueChange: '+6%',
      totalOrders: '650',
      totalOrdersChange: '+2%',
      avgDailyRevenue: '৳10,330',
      avgDailyRevenueChange: '+1%',
    },
    branchesList: [],
    assignedStaff: [
      {
        id: 'st-bar1',
        name: 'Nadia Chowdhury',
        role: 'Manager',
        avatar: 'NC',
        restaurantName: 'The Barrel Bar',
        days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        status: 'Active',
      },
      {
        id: 'st-bar2',
        name: 'Ryan Hayes',
        role: 'Mixologist',
        avatar: 'RH',
        restaurantName: 'The Barrel Bar',
        days: ['Thu', 'Fri', 'Sat'],
        status: 'Active',
      },
    ],
    menuItems: [
      {
        id: 'menu-bar1',
        name: 'Smoked Old Fashioned',
        category: 'Signature Drinks',
        price: '৳650',
        status: 'Available',
      },
      {
        id: 'menu-bar2',
        name: 'Truffle Potato Wedges',
        category: 'Bites',
        price: '৳310',
        status: 'Available',
      },
    ],
  },
];

export const INITIAL_BRANCHES: Record<string, BranchItem[]> = {
  'rest-1': [
    {
      id: 'b-rest-1-1',
      restaurantId: 'rest-1',
      restaurantName: 'Tavonza Downtown',
      name: 'Tavonza Uttara',
      address: 'Sector 4, Uttara',
      city: 'Uttara',
      country: 'Dhaka',
      postalCode: '1230',
      phone: '+880 1711-112233',
      email: 'uttara@tavonza.com',
      status: 'Open',
      manager: {
        id: 'mgr-u',
        name: 'Arif Hossain',
        role: 'Branch Manager',
        email: 'arif@tavonza.com',
        avatar: 'AH',
      },
      staffCount: 7,
      assignedStaff: [],
    },
    {
      id: 'b-rest-1-2',
      restaurantId: 'rest-1',
      restaurantName: 'Tavonza Downtown',
      name: 'Tavonza Mirpur',
      address: 'Section 10, Mirpur',
      city: 'Mirpur',
      country: 'Dhaka',
      postalCode: '1216',
      phone: '+880 1722-223344',
      email: 'mirpur@tavonza.com',
      status: 'Closed',
      manager: {
        id: 'mgr-m',
        name: 'Priya Sen',
        role: 'Branch Supervisor',
        email: 'priya@tavonza.com',
        avatar: 'PS',
      },
      staffCount: 5,
      assignedStaff: [],
    },
  ],
};
