import { POSProduct, POSCategory, POSCartItem } from './types';

export const POS_CATEGORIES: POSCategory[] = [
  'All',
  'Burgers',
  'Pizza',
  'Pasta',
  'Salads',
  'Desserts',
  'Drinks',
];

export const POS_TABLES: string[] = [
  'T-01', 'T-02', 'T-03', 'T-04', 'T-05',
  'T-06', 'T-07', 'T-08', 'T-09', 'T-10',
  'T-11', 'T-12', 'T-13', 'T-14', 'T-15',
  'Bar-01', 'Bar-02', 'VIP-01', 'Patio-01'
];

export const POS_PRODUCTS: POSProduct[] = [
  {
    id: 'pos-1',
    name: 'Smokey Salmon',
    category: 'Burgers',
    categoryLabel: 'Rolls',
    price: 18.5,
    image: '/assets/costomerpages/steak-rating-card.png',
    isHot: true,
    badge: 'Hot',
    emoji: '🍣',
  },
  {
    id: 'pos-2',
    name: 'Classic Burger',
    category: 'Burgers',
    categoryLabel: 'Burgers',
    price: 18.5,
    image: '/assets/costomerpages/ribeye-steak-butter.png',
    isHot: true,
    badge: 'Hot',
    emoji: '🍔',
  },
  {
    id: 'pos-3',
    name: 'Mini Pancakes',
    category: 'Desserts',
    categoryLabel: 'Pancakes',
    price: 18.5,
    image: '/assets/costomerpages/sliced-flank-steak.png',
    isHot: false,
    emoji: '🥞',
  },
  {
    id: 'pos-4',
    name: 'Sushi Rolls',
    category: 'Burgers',
    categoryLabel: 'Rolls',
    price: 18.5,
    image: '/assets/costomerpages/tomahawk-ribeye-steak.png',
    isHot: true,
    badge: 'Hot',
    emoji: '🍱',
  },
  {
    id: 'pos-5',
    name: 'Margherita Pizza',
    category: 'Pizza',
    categoryLabel: 'Pizza',
    price: 19.5,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: true,
    badge: 'Hot',
    emoji: '🍕',
  },
  {
    id: 'pos-6',
    name: 'Greek Salad',
    category: 'Salads',
    categoryLabel: 'Salads',
    price: 13.0,
    image: '/assets/costomerpages/fine-dining-wine-table.jpg',
    isHot: false,
    emoji: '🥗',
  },
  {
    id: 'pos-7',
    name: 'Truffle Alfredo',
    category: 'Pasta',
    categoryLabel: 'Pasta',
    price: 22.5,
    image: '/assets/costomerpages/filet-mignon-steak.png',
    isHot: true,
    badge: 'Hot',
    emoji: '🍝',
  },
  {
    id: 'pos-8',
    name: 'Caesar Salad',
    category: 'Salads',
    categoryLabel: 'Salads',
    price: 14.5,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: false,
    emoji: '🥗',
  },
  {
    id: 'pos-9',
    name: 'Tiramisu Classico',
    category: 'Desserts',
    categoryLabel: 'Desserts',
    price: 12.0,
    image: '/assets/costomerpages/ribeye-steak-butter.png',
    isHot: false,
    emoji: '🍰',
  },
  {
    id: 'pos-10',
    name: 'Fresh Lemonade',
    category: 'Drinks',
    categoryLabel: 'Drinks',
    price: 6.5,
    image: '/assets/costomerpages/fine-dining-wine-table.jpg',
    isHot: false,
    emoji: '🍋',
  },
  {
    id: 'pos-11',
    name: 'Iced Caramel Latte',
    category: 'Drinks',
    categoryLabel: 'Drinks',
    price: 7.0,
    image: '/assets/costomerpages/steak-rating-card.png',
    isHot: false,
    emoji: '☕',
  },
  {
    id: 'pos-12',
    name: 'Sparkling Water',
    category: 'Drinks',
    categoryLabel: 'Drinks',
    price: 5.0,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: false,
    emoji: '💧',
  },
];

// Initial cart items matching Figma screen #2 ($56.16 total)
export const INITIAL_CART_ITEMS: POSCartItem[] = [
  {
    product: (POS_PRODUCTS.find((p) => p.name === 'Margherita Pizza') || POS_PRODUCTS[4])!,
    quantity: 2,
  },
  {
    product: (POS_PRODUCTS.find((p) => p.name === 'Greek Salad') || POS_PRODUCTS[5])!,
    quantity: 1,
  },
];
