import { CashierOrder, BillQueueItem } from "./types";

export const initialCashierOrders: CashierOrder[] = [
  {
    id: "ord-1220",
    orderNumber: "#1220",
    totalAmount: 20.12,
    tableNumber: "Table 1",
    guestCount: 4,
    waitTime: "4m wait",
    customerName: "James L",
    itemCount: 3,
    subtotal: 16.71,
    serviceCharge: 1.93,
    tax: 1.48,
    kitchenStatus: "READY_TO_SERVE",
    financeStatus: "REQUESTING_CASH",
    paymentDate: "September 28, at 07:30 pm",
    paymentMethod: "Cash",
    items: [
      { id: "i1", name: "Potato Corn Burger", price: 16.00, quantity: 1 },
      { id: "i2", name: "Iced Tea", price: 2.50, quantity: 1 },
      { id: "i3", name: "French Fries", price: 1.62, quantity: 1 },
    ],
  },
  {
    id: "ord-1230",
    orderNumber: "#1230",
    totalAmount: 46.27,
    tableNumber: "Table 2",
    guestCount: 2,
    waitTime: "4m wait",
    customerName: "Sarah M.",
    itemCount: 3,
    subtotal: 28.30,
    serviceCharge: 1.93,
    tax: 1.48,
    kitchenStatus: "PREPARING",
    financeStatus: "NOT_PAID",
    paymentDate: "September 28, at 07:30 pm",
    paymentMethod: "Cash",
    items: [
      { id: "i4", name: "Potato Corn Burger", price: 16.00, quantity: 1 },
      { id: "i5", name: "Crispy Fries & Dip", price: 12.30, quantity: 1 },
      { id: "i6", name: "Soda Fountain", price: 3.50, quantity: 1 },
    ],
  },
  {
    id: "ord-1210",
    orderNumber: "#1210",
    totalAmount: 60.52,
    tableNumber: "Table 1",
    guestCount: 1,
    waitTime: "4m wait",
    customerName: "Alex",
    itemCount: 2,
    subtotal: 52.00,
    serviceCharge: 4.50,
    tax: 4.02,
    kitchenStatus: "COMPLETED",
    financeStatus: "NOT_PAID",
    paymentDate: "September 28, at 07:30 pm",
    paymentMethod: "Cash",
    items: [
      { id: "i7", name: "Ribeye Steak 300g", price: 42.00, quantity: 1 },
      { id: "i8", name: "Red Wine Glass", price: 10.00, quantity: 1 },
    ],
  },
];

export const initialBillQueueItems: BillQueueItem[] = [
  {
    id: "bq-10590",
    orderNumber: "#10590",
    tableNumber: "#01",
    customerName: "Sarah M.",
    itemCount: 3,
    paymentMethod: "Visa Card",
    status: "Preparing",
    total: 18.50,
    subtotal: 15.00,
    tax: 1.50,
    serviceCharge: 2.00,
    time: "10m ago",
    items: [
      { name: "Caesar Salad", price: 10.00, quantity: 1 },
      { name: "Iced Latte", price: 5.00, quantity: 1 },
    ],
  },
  {
    id: "bq-10591",
    orderNumber: "#10591",
    tableNumber: "#02",
    customerName: "Sarah M.",
    itemCount: 2,
    paymentMethod: "Cash",
    status: "Ready",
    total: 28.50,
    subtotal: 24.00,
    tax: 2.50,
    serviceCharge: 2.00,
    time: "5m ago",
    items: [
      { name: "Potato Corn Burger", price: 16.00, quantity: 1 },
      { name: "Crispy Fries", price: 8.00, quantity: 1 },
    ],
  },
  {
    id: "bq-10592",
    orderNumber: "#10592",
    tableNumber: "#03",
    customerName: "Sarah M.",
    itemCount: 4,
    paymentMethod: "Digital Wallet",
    status: "Pending",
    total: 45.00,
    subtotal: 38.00,
    tax: 4.00,
    serviceCharge: 3.00,
    time: "12m ago",
    items: [
      { name: "Ribeye Steak 300g", price: 32.00, quantity: 1 },
      { name: "Soda Fountain", price: 6.00, quantity: 2 },
    ],
  },
  {
    id: "bq-10593",
    orderNumber: "#10593",
    tableNumber: "#04",
    customerName: "Sarah M.",
    itemCount: 1,
    paymentMethod: "Visa Card",
    status: "Payment Pending",
    total: 12.00,
    subtotal: 10.00,
    tax: 1.00,
    serviceCharge: 1.00,
    time: "18m ago",
    items: [{ name: "Beef Stack Burger", price: 10.00, quantity: 1 }],
  },
  {
    id: "bq-10594",
    orderNumber: "#10594",
    tableNumber: "#05",
    customerName: "Sarah M.",
    itemCount: 5,
    paymentMethod: "Cash",
    status: "Needs Attention",
    total: 64.20,
    subtotal: 54.00,
    tax: 5.20,
    serviceCharge: 5.00,
    time: "25m ago",
    items: [
      { name: "Grilled Salmon", price: 28.00, quantity: 1 },
      { name: "White Wine Glass", price: 12.00, quantity: 1 },
      { name: "Chocolate Cake", price: 14.00, quantity: 1 },
    ],
  },
  {
    id: "bq-10595",
    orderNumber: "#10595",
    tableNumber: "#06",
    customerName: "Sarah M.",
    itemCount: 2,
    paymentMethod: "Digital Wallet",
    status: "Ordering",
    total: 32.00,
    subtotal: 27.00,
    tax: 3.00,
    serviceCharge: 2.00,
    time: "2m ago",
    items: [
      { name: "Club Sandwich", price: 18.00, quantity: 1 },
      { name: "Fresh OJ", price: 9.00, quantity: 1 },
    ],
  },
];
