import { POSProduct, POSCategory } from './types';

export const POS_CATEGORIES: POSCategory[] = [
  'All',
  'Burgers',
  'Pizza',
  'Pasta',
  'Salads',
  'Desserts',
  'Drinks',
];

export const POS_TABLES = [
  'T-01', 'T-02', 'T-03', 'T-04', 'T-05',
  'T-06', 'T-07', 'T-08', 'T-09', 'T-10',
  'T-11', 'T-12', 'T-13', 'T-14', 'T-15',
  'Bar-01', 'Bar-02', 'VIP-01', 'Patio-01'
];

export const INITIAL_POS_PRODUCTS: POSProduct[] = [
  {
    id: 'pos-1',
    name: 'Smokey Salmon',
    category: 'Burgers',
    categoryLabel: 'Rolls',
    price: 18.5,
    image: '/assets/costomerpages/steak-rating-card.png',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-2',
    name: 'Classic Burger',
    category: 'Burgers',
    categoryLabel: 'Burgers',
    price: 18.5,
    image: '/assets/costomerpages/ribeye-steak-butter.png',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-3',
    name: 'Mini Pancakes',
    category: 'Desserts',
    categoryLabel: 'Pancakes',
    price: 18.5,
    image: '/assets/costomerpages/sliced-flank-steak.png',
    isHot: false,
  },
  {
    id: 'pos-4',
    name: 'Sushi Rolls',
    category: 'Burgers',
    categoryLabel: 'Rolls',
    price: 18.5,
    image: '/assets/costomerpages/tomahawk-ribeye-steak.png',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-5',
    name: 'Margherita Pizza',
    category: 'Pizza',
    categoryLabel: 'Pizza',
    price: 19.5,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-6',
    name: 'Chicken BBQ Pizza',
    category: 'Pizza',
    categoryLabel: 'Pizza',
    price: 21.0,
    image: '/assets/costomerpages/fine-dining-wine-table.jpg',
    isHot: false,
  },
  {
    id: 'pos-7',
    name: 'Truffle Alfredo',
    category: 'Pasta',
    categoryLabel: 'Pasta',
    price: 22.5,
    image: '/assets/costomerpages/filet-mignon-steak.png',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-8',
    name: 'Spaghetti Bolognese',
    category: 'Pasta',
    categoryLabel: 'Pasta',
    price: 18.5,
    image: '/assets/costomerpages/sliced-flank-steak.png',
    isHot: false,
  },
  {
    id: 'pos-9',
    name: 'Caesar Salad',
    category: 'Salads',
    categoryLabel: 'Salads',
    price: 14.5,
    image: '/assets/costomerpages/steak-rating-card.png',
    isHot: false,
  },
  {
    id: 'pos-10',
    name: 'Greek Feta Salad',
    category: 'Salads',
    categoryLabel: 'Salads',
    price: 15.0,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: false,
  },
  {
    id: 'pos-11',
    name: 'Tiramisu Classico',
    category: 'Desserts',
    categoryLabel: 'Desserts',
    price: 12.0,
    image: '/assets/costomerpages/ribeye-steak-butter.png',
    isHot: false,
  },
  {
    id: 'pos-12',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    categoryLabel: 'Desserts',
    price: 13.5,
    image: '/assets/costomerpages/filet-mignon-steak.png',
    isHot: true,
    badge: 'Hot',
  },
  {
    id: 'pos-13',
    name: 'Fresh Lemonade',
    category: 'Drinks',
    categoryLabel: 'Beverages',
    price: 6.5,
    image: '/assets/costomerpages/fine-dining-wine-table.jpg',
    isHot: false,
  },
  {
    id: 'pos-14',
    name: 'Iced Caramel Latte',
    category: 'Drinks',
    categoryLabel: 'Coffee',
    price: 7.0,
    image: '/assets/costomerpages/steak-rating-card.png',
    isHot: false,
  },
  {
    id: 'pos-15',
    name: 'Sparkling Mineral Water',
    category: 'Drinks',
    categoryLabel: 'Beverages',
    price: 5.0,
    image: '/assets/costomerpages/restaurant-table-spread.jpg',
    isHot: false,
  },
  {
    id: 'pos-16',
    name: 'BBQ Bacon Burger',
    category: 'Burgers',
    categoryLabel: 'Burgers',
    price: 20.0,
    image: '/assets/costomerpages/tomahawk-ribeye-steak.png',
    isHot: true,
    badge: 'Hot',
  },
];
