import { QRTableItem } from './types';

export const INITIAL_QR_TABLES: QRTableItem[] = [
  {
    id: 'T-01',
    number: '01',
    seats: 2,
    zone: 'Main Hall',
    status: 'Busy',
    server: 'Jake R.',
    url: 'order.tavonza.ai/t/t-01',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 5,
    lastScanTime: '4 min ago',
    seatedMinutesAgo: 28,
    liveOrder: {
      itemsCount: 2,
      subtotal: 43.5,
      items: [
        { id: '1', name: 'Margherita Pizza', qty: 1, price: 14.5, status: 'served' },
        { id: '2', name: 'Tiramisu', qty: 2, price: 29.0, status: 'ready' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Order placed via QR — 3 items', time: '2:48 PM', type: 'amber' },
      { id: 'l2', text: 'Table seated — party of 3', time: '2:31 PM', type: 'emerald' },
      { id: 'l3', text: 'QR code scanned by guest', time: '2:30 PM', type: 'blue' },
      { id: 'l4', text: 'Previous party departed', time: '1:18 PM', type: 'gray' },
    ],
  },
  {
    id: 'T-02',
    number: '02',
    seats: 2,
    zone: 'Main Hall',
    status: 'Free',
    server: 'Jake R.',
    url: 'order.tavonza.ai/t/t-02',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 3,
    lastScanTime: '22 min ago',
    seatedMinutesAgo: 0,
    liveOrder: undefined,
    activityLogs: [
      { id: 'l1', text: 'Table cleared & sanitized', time: '2:15 PM', type: 'emerald' },
      { id: 'l2', text: 'Guest paid $38.00 via Apple Pay', time: '2:10 PM', type: 'blue' },
    ],
  },
  {
    id: 'T-03',
    number: '03',
    seats: 4,
    zone: 'Main Hall',
    status: 'Busy',
    server: 'Sarah M.',
    url: 'order.tavonza.ai/t/t-03',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 8,
    lastScanTime: '2 min ago',
    seatedMinutesAgo: 14,
    liveOrder: {
      itemsCount: 3,
      subtotal: 58.0,
      items: [
        { id: '1', name: 'Classic Truffle Burger', qty: 2, price: 37.0, status: 'cooking' },
        { id: '2', name: 'Fresh Lemonade', qty: 2, price: 21.0, status: 'served' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Drink items delivered', time: '2:52 PM', type: 'emerald' },
      { id: 'l2', text: 'Order sent to Kitchen display', time: '2:49 PM', type: 'amber' },
    ],
  },
  {
    id: 'T-04',
    number: '04',
    seats: 4,
    zone: 'Patio',
    status: 'Free',
    server: 'Sarah M.',
    url: 'order.tavonza.ai/t/t-04',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 2,
    lastScanTime: '45 min ago',
    seatedMinutesAgo: 0,
    liveOrder: undefined,
    activityLogs: [
      { id: 'l1', text: 'Table set for outdoor seating', time: '1:45 PM', type: 'emerald' },
    ],
  },
  {
    id: 'T-05',
    number: '05',
    seats: 6,
    zone: 'Patio',
    status: 'Busy',
    server: 'Alex T.',
    url: 'order.tavonza.ai/t/t-05',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 6,
    lastScanTime: '10 min ago',
    seatedMinutesAgo: 40,
    liveOrder: {
      itemsCount: 4,
      subtotal: 82.5,
      items: [
        { id: '1', name: 'Smokey Salmon Carpaccio', qty: 2, price: 37.0, status: 'served' },
        { id: '2', name: 'Quattro Formaggi Pizza', qty: 2, price: 45.5, status: 'served' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Dessert menu requested', time: '2:55 PM', type: 'amber' },
      { id: 'l2', text: 'Mains served by server Alex', time: '2:40 PM', type: 'emerald' },
    ],
  },
  {
    id: 'T-06',
    number: '06',
    seats: 2,
    zone: 'VIP Lounge',
    status: 'Busy',
    server: 'Alex T.',
    url: 'order.tavonza.ai/t/t-06',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 4,
    lastScanTime: '6 min ago',
    seatedMinutesAgo: 18,
    liveOrder: {
      itemsCount: 2,
      subtotal: 64.0,
      items: [
        { id: '1', name: 'Premium Ribeye Steak', qty: 1, price: 48.0, status: 'cooking' },
        { id: '2', name: 'Red Wine Reserve', qty: 1, price: 16.0, status: 'served' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Wine served to table', time: '2:45 PM', type: 'emerald' },
      { id: 'l2', text: 'VIP guest seated', time: '2:35 PM', type: 'blue' },
    ],
  },
  {
    id: 'T-07',
    number: '07',
    seats: 4,
    zone: 'Main Hall',
    status: 'Free',
    server: 'Jake R.',
    url: 'order.tavonza.ai/t/t-07',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 1,
    lastScanTime: '1 hr ago',
    seatedMinutesAgo: 0,
    liveOrder: undefined,
    activityLogs: [],
  },
  {
    id: 'T-08',
    number: '08',
    seats: 4,
    zone: 'Main Hall',
    status: 'Busy',
    server: 'Sarah M.',
    url: 'order.tavonza.ai/t/t-08',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 7,
    lastScanTime: '12 min ago',
    seatedMinutesAgo: 32,
    liveOrder: {
      itemsCount: 3,
      subtotal: 51.5,
      items: [
        { id: '1', name: 'Rigatoni Truffle Pasta', qty: 2, price: 39.0, status: 'served' },
        { id: '2', name: 'Mineral Water', qty: 2, price: 12.5, status: 'served' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Bill requested via QR menu', time: '2:56 PM', type: 'amber' },
    ],
  },
  {
    id: 'T-09',
    number: '09',
    seats: 8,
    zone: 'VIP Lounge',
    status: 'Free',
    server: 'Alex T.',
    url: 'order.tavonza.ai/t/t-09',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 2,
    lastScanTime: '2 hrs ago',
    seatedMinutesAgo: 0,
    liveOrder: undefined,
    activityLogs: [],
  },
  {
    id: 'T-10',
    number: '10',
    seats: 2,
    zone: 'Bar Area',
    status: 'Busy',
    server: 'Elena K.',
    url: 'order.tavonza.ai/t/t-10',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 9,
    lastScanTime: '1 min ago',
    seatedMinutesAgo: 10,
    liveOrder: {
      itemsCount: 2,
      subtotal: 32.0,
      items: [
        { id: '1', name: 'Craft Cocktail Duo', qty: 2, price: 32.0, status: 'ready' },
      ],
    },
    activityLogs: [
      { id: 'l1', text: 'Bar order ready for pickup', time: '2:57 PM', type: 'emerald' },
    ],
  },
  {
    id: 'T-11',
    number: '11',
    seats: 2,
    zone: 'Bar Area',
    status: 'Free',
    server: 'Elena K.',
    url: 'order.tavonza.ai/t/t-11',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 4,
    lastScanTime: '30 min ago',
    seatedMinutesAgo: 0,
    liveOrder: undefined,
    activityLogs: [],
  },
  {
    id: 'T-12',
    number: '12',
    seats: 4,
    zone: 'Patio',
    status: 'Busy',
    server: 'Jake R.',
    url: 'order.tavonza.ai/t/t-12',
    qrActiveVersion: 'Yes — v3 (Jul 2026)',
    scansToday: 5,
    lastScanTime: '8 min ago',
    seatedMinutesAgo: 22,
    liveOrder: {
      itemsCount: 2,
      subtotal: 41.0,
      items: [
        { id: '1', name: 'BBQ Bacon Burger', qty: 2, price: 41.0, status: 'cooking' },
      ],
    },
    activityLogs: [],
  },
];
