import { PaymentTransaction } from './types';

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'TXN-8821',
    orderId: '#10480',
    customerName: 'Olivia Martinez',
    tableId: 'T-11',
    method: 'Card',
    server: 'Aisha B.',
    time: '4:35 PM',
    tipAmount: 20.5,
    status: 'completed',
    amount: 92.0,
  },
  {
    id: 'TXN-8822',
    orderId: '#10479',
    customerName: 'Noah Thompson',
    tableId: 'T-02',
    method: 'Cash',
    server: 'Carlos M.',
    time: '3:52 PM',
    tipAmount: 15.5,
    status: 'completed',
    amount: 64.0,
  },
  {
    id: 'TXN-8823',
    orderId: '#10478',
    customerName: 'James Williams',
    tableId: 'T-15',
    method: 'Card',
    server: 'Maria L.',
    time: '3:30 PM',
    tipAmount: 0,
    status: 'refunded',
    amount: 52.0,
  },
  {
    id: 'TXN-8824',
    orderId: '#10477',
    customerName: 'Isabella Davis',
    tableId: 'T-08',
    method: 'Digital',
    server: 'Jake R.',
    time: '3:25 PM',
    tipAmount: 10.5,
    status: 'completed',
    amount: 56.0,
  },
  {
    id: 'TXN-8825',
    orderId: '#10476',
    customerName: 'William Brown',
    tableId: 'T-04',
    method: 'Digital',
    server: 'Carlos M.',
    time: '2:40 PM',
    tipAmount: 15.5,
    status: 'completed',
    amount: 40.0,
  },
  {
    id: 'TXN-8826',
    orderId: '#10475',
    customerName: 'Sophia Garcia',
    tableId: 'T-09',
    method: 'Cash',
    server: 'Aisha B.',
    time: '2:30 PM',
    tipAmount: 12.5,
    status: 'completed',
    amount: 92.0,
  },
  {
    id: 'TXN-8827',
    orderId: '#10474',
    customerName: 'Benjamin Wilson',
    tableId: 'T-01',
    method: 'Cash',
    server: 'Carlos M.',
    time: '1:45 PM',
    tipAmount: 10.5,
    status: 'completed',
    amount: 95.0,
  },
  {
    id: 'TXN-8828',
    orderId: '#10473',
    customerName: 'Mia Anderson',
    tableId: 'T-12',
    method: 'Card',
    server: 'Jake R.',
    time: '1:20 PM',
    tipAmount: 16.5,
    status: 'completed',
    amount: 84.0,
  },
  {
    id: 'TXN-8829',
    orderId: '#10472',
    customerName: 'Charlotte Lee',
    tableId: 'T-06',
    method: 'Digital',
    server: 'Maria L.',
    time: '1:00 PM',
    tipAmount: 20.5,
    status: 'completed',
    amount: 45.0,
  },
  {
    id: 'TXN-8830',
    orderId: '#10471',
    customerName: 'Amelia Scott',
    tableId: 'T-05',
    method: 'Card',
    server: 'Carlos M.',
    time: '12:50 PM',
    tipAmount: 16.5,
    status: 'completed',
    amount: 90.0,
  },
  {
    id: 'TXN-8831',
    orderId: '#10470',
    customerName: 'Henry Adams',
    tableId: 'T-13',
    method: 'Cash',
    server: 'Maria L.',
    time: '12:30 PM',
    tipAmount: 10.5,
    status: 'Pending',
    amount: 85.0,
  },
  {
    id: 'TXN-8834',
    orderId: '#10469',
    customerName: 'Lucas Taylor',
    tableId: 'T-14',
    method: 'Card',
    server: 'Carlos M.',
    time: '12:05 PM',
    tipAmount: 10.5,
    status: 'completed',
    amount: 92.0,
  },
  {
    id: 'TXN-8835',
    orderId: '#10468',
    customerName: 'Giana Workman',
    tableId: 'T-10',
    method: 'Digital',
    server: 'Jake R.',
    time: '11:55 AM',
    tipAmount: 12.5,
    status: 'completed',
    amount: 19.8,
  },
  {
    id: 'TXN-8832',
    orderId: '#10467',
    customerName: 'Justin Calzoni',
    tableId: 'T-08',
    method: 'Card',
    server: 'Carlos M.',
    time: '11:40 AM',
    tipAmount: 16.5,
    status: 'refunded',
    amount: 92.0,
  },
  {
    id: 'TXN-8833',
    orderId: '#10466',
    customerName: 'Terry Lipshutz',
    tableId: 'T-08',
    method: 'Cash',
    server: 'Aisha B.',
    time: '11:20 AM',
    tipAmount: 20.5,
    status: 'completed',
    amount: 44.6,
  },
];
