import { CampaignItem, MarketingKPI, AudienceOption } from './types';

export const INITIAL_MARKETING_KPIS: MarketingKPI[] = [
  {
    id: 'kpi-1',
    title: 'Active Campaigns',
    value: '02',
    change: '+1 this month',
    isPositive: true,
    subtext: 'Active Campaigns',
  },
  {
    id: 'kpi-2',
    title: 'Messages Sent',
    value: '3,240',
    change: '+18.4% vs last week',
    isPositive: true,
    subtext: 'Messages Sent',
  },
  {
    id: 'kpi-3',
    title: 'Avg Open Rate',
    value: '61%',
    change: '+5.2% vs industry avg',
    isPositive: true,
    subtext: 'Avg Open Rate',
  },
  {
    id: 'kpi-4',
    title: 'Revenue Attributed',
    value: '$16,440',
    change: 'ROAS 14.8x',
    isPositive: true,
    subtext: 'Revenue Attributed',
  },
];

export const INITIAL_CAMPAIGNS: CampaignItem[] = [
  {
    id: 'camp-1',
    name: 'Weekend Burger Promo',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'All Customers',
    messageContent: '🍔 Craving something special this weekend? Enjoy 20% OFF our award-winning Classic Burger & Craft Shakes! Show this text to redeem: BKEND20. Valid Fri-Sun.',
    deliveryRate: 98.6,
    clickRate: 38.4,
    conversionsCount: 168,
    cost: 32.5,
  },
  {
    id: 'camp-2',
    name: 'Loyalty Points Boost',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'All Loyalty Members',
    messageContent: '✨ Double points weekend! Order your favorites tonight and earn 2X Tavonza Reward points toward free desserts and entrees. Tap to book your table: tavonza.com/book',
    deliveryRate: 99.1,
    clickRate: 42.1,
    conversionsCount: 185,
    cost: 32.5,
  },
  {
    id: 'camp-3',
    name: 'VIP Early Access Dinner',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'VIP Customers',
    messageContent: '🍷 Exclusive Invitation: Chef Marco is previewing our Summer Truffle & Wine pairing menu before public launch. Reserve your private booth now: tavonza.com/vip',
    deliveryRate: 99.4,
    clickRate: 51.6,
    conversionsCount: 112,
    cost: 32.5,
  },
  {
    id: 'camp-4',
    name: 'Feedback Request',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'Recent Visitors',
    messageContent: '⭐ Thank you for dining with Tavonza! How was your experience? Leave a quick review and get a complimentary appetizer on your next visit: tavonza.com/review',
    deliveryRate: 98.2,
    clickRate: 31.0,
    conversionsCount: 94,
    cost: 32.5,
  },
  {
    id: 'camp-5',
    name: 'New Menu Launch',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'Regular Customers',
    messageContent: '🔥 New Flavors Alert! Introducing 6 seasonal summer dishes inspired by Amsterdam & Italian culinary traditions. Come taste what is new: tavonza.com/menu',
    deliveryRate: 97.9,
    clickRate: 35.8,
    conversionsCount: 140,
    cost: 32.5,
  },
  {
    id: 'camp-6',
    name: 'Weekend Burger Promo',
    channel: 'SMS',
    date: 'Jul 10, 2025',
    status: 'Active',
    sentCount: 840,
    openRate: 72,
    revenue: 2340,
    targetAudience: 'New Customers',
    messageContent: '🍔 Welcome to Tavonza! Kick off your culinary journey with a complimentary handcrafted drink with any artisan burger. Use code: WELCOMEBURGER.',
    deliveryRate: 98.8,
    clickRate: 39.2,
    conversionsCount: 156,
    cost: 32.5,
  },
];

export const AUDIENCE_OPTIONS: AudienceOption[] = [
  {
    id: 'all',
    name: 'All Customers',
    count: 2450,
    description: 'Complete customer database across all channels',
  },
  {
    id: 'vip',
    name: 'VIP Customers',
    count: 320,
    description: 'Top 10% spenders and frequent diners (>$500/yr)',
  },
  {
    id: 'regular',
    name: 'Regular Customers',
    count: 890,
    description: 'Customers who visited 3+ times in the last 60 days',
  },
  {
    id: 'new',
    name: 'New Customers',
    count: 410,
    description: 'First-time diners within the last 30 days',
  },
  {
    id: 'loyalty',
    name: 'All Loyalty Members',
    count: 1280,
    description: 'Enrolled members with active point balances',
  },
  {
    id: 'recent',
    name: 'Recent Visitors',
    count: 560,
    description: 'Customers who checked in or ordered in past 7 days',
  },
];

export const AI_SUGGESTED_TEMPLATES = [
  {
    title: 'Weekend Flash Promo',
    channel: 'SMS' as const,
    audience: 'All Customers',
    message: '🎉 Weekend Special: Enjoy 20% OFF all signature burgers and craft beverages this Sat & Sun! Show text to redeem. Code: TAVONZA20.',
  },
  {
    title: 'VIP Tasting Menu Invite',
    channel: 'Email' as const,
    audience: 'VIP Customers',
    message: '✨ Exclusive VIP Invitation: Join our Executive Chef for an intimate 5-course seasonal tasting with private wine pairings. Reserve now.',
  },
  {
    title: 'Happy Hour Push Alert',
    channel: 'Push' as const,
    audience: 'Recent Visitors',
    message: '🍸 Happy Hour starts in 30 mins! 2-for-1 cocktails & $8 artisanal bites at Downtown Tavonza. Your table is waiting!',
  },
  {
    title: 'Loyalty Tier Accelerator',
    channel: 'SMS' as const,
    audience: 'All Loyalty Members',
    message: '🌟 Earn 3X points on all orders over $40 today only! Level up to Gold Tier faster and unlock free chef specials.',
  },
];
