import {
  TableItem,
  OrderItemRow,
  StaffCardData,
  KdsTicket,
  ManagerProfile,
  PaymentRecord,
  PaymentSummaryKpi,
  MenuItem,
} from './types';

export const mockManagerProfile: ManagerProfile = {
  name: 'Nobin Mille',
  role: 'Branch Manager',
  branch: 'Downtown Flagship',
};

export const INITIAL_TABLES: TableItem[] = [
  {
    id: 'T01',
    number: 'T01',
    status: 'available',
    capacity: 2,
  },
  {
    id: 'T02',
    number: 'T02',
    status: 'occupied',
    waiter: 'Alex',
    itemsCount: 3,
    orderNumber: 'Order #1030',
    orderTime: '5m',
    capacity: 4,
  },
  {
    id: 'T04',
    number: 'T04',
    status: 'preparing',
    waiter: 'Sara',
    itemsCount: 3,
    orderNumber: 'Order #1042',
    orderTime: '22m',
    capacity: 4,
  },
  {
    id: 'T05',
    number: 'T05',
    status: 'need_attention',
    waiter: 'Sara',
    itemsCount: 2,
    orderNumber: 'Order #1038',
    orderTime: '45m',
    capacity: 6,
  },
  {
    id: 'T06',
    number: 'T06',
    status: 'ready',
    waiter: 'Alex',
    itemsCount: 3,
    orderNumber: 'Order #1045',
    orderTime: '55m',
    capacity: 4,
  },
  {
    id: 'T12',
    number: 'T12',
    status: 'payment',
    waiter: 'Alex',
    itemsCount: 3,
    orderNumber: 'Order #1030',
    orderTime: '55m',
    capacity: 2,
  },
  {
    id: 'T03',
    number: 'T03',
    status: 'available',
    capacity: 4,
  },
  {
    id: 'T07',
    number: 'T07',
    status: 'occupied',
    waiter: 'Mello',
    itemsCount: 4,
    orderNumber: 'Order #1048',
    orderTime: '15m',
    capacity: 6,
  },
];

export const INITIAL_ORDERS: OrderItemRow[] = [
  {
    id: '1042',
    orderNumber: '#1042',
    waiterLocation: 'Table 01',
    items: 'Grilled Chicken',
    timeElapsed: '22m ago',
    status: 'Preparing',
    total: '$18.50',
  },
  {
    id: '1043',
    orderNumber: '#1043',
    waiterLocation: 'Table 03',
    items: '2X Mojito',
    timeElapsed: '14m ago',
    status: 'Ready',
    total: '$18.50',
  },
  {
    id: '1044',
    orderNumber: '#1044',
    waiterLocation: 'Marcus Vance',
    items: 'Truffle Fries',
    timeElapsed: '14m ago',
    status: 'Pending',
    total: '$18.50',
  },
  {
    id: '1045',
    orderNumber: '#1045',
    waiterLocation: 'Table 06',
    items: 'Pasta Carbonara',
    timeElapsed: '55m ago',
    isUrgent: true,
    status: 'Payment Pending',
    total: '$18.50',
  },
  {
    id: '1046',
    orderNumber: '#1046',
    waiterLocation: 'Table 07',
    items: 'Wagyu Sliders',
    timeElapsed: '45m ago',
    isUrgent: true,
    status: 'Needs Attention',
    total: '$18.50',
  },
  {
    id: '1047',
    orderNumber: '#1047',
    waiterLocation: 'Table 08',
    items: 'Mutton Stack',
    timeElapsed: '5m ago',
    status: 'Ordering',
    total: '$18.50',
  },
  {
    id: '10590',
    orderNumber: '#10590',
    waiterLocation: 'Table 02',
    items: 'Margherita Pizza, Sparkling Water',
    timeElapsed: '12m ago',
    status: 'Completed',
    total: '$24.00',
  },
];

export const INITIAL_STAFF: StaffCardData[] = [
  {
    id: 'sarah-miller',
    name: 'Sarah Miller',
    role: 'Waiters',
    status: 'Active',
    currentShift: 'Lunch Shift (8:00 AM - 4:00PM)',
    currentAssignment: 'Floor Section A',
    stationTables: 'Table 01, 02',
    clockInTime: '09:55 AM',
  },
  {
    id: 'marcus-vance',
    name: 'Marcus Vance',
    role: 'Waiters',
    status: 'Active',
    currentShift: 'Lunch Shift (8:00 AM - 4:00PM)',
    currentAssignment: 'Floor Section B',
    stationTables: 'Table 03, 04',
    clockInTime: '10:02 AM',
  },
  {
    id: 'elena',
    name: 'Elena',
    role: 'Kitchen',
    status: 'Break',
    currentShift: 'Lunch Shift (8:00 AM - 4:00PM)',
    currentAssignment: 'Cold Prep & Desserts',
    stationTables: 'Cold & Dessert Station',
    clockInTime: '09:50 AM',
  },
  {
    id: 'liam',
    name: 'Liam',
    role: 'Bartenders',
    status: 'Active',
    currentShift: 'Lunch Shift (10:00 AM - 5:00PM)',
    currentAssignment: 'Main Bar & Beverage Line',
    stationTables: 'Bar Station',
    clockInTime: '10:25 AM',
  },
  {
    id: 'chloe',
    name: 'Chloe',
    role: 'Cashiers',
    status: 'Active',
    currentShift: 'Lunch Shift (10:00 AM - 5:00PM)',
    currentAssignment: 'Front Counter & Take POS',
    stationTables: 'Counter Register #1',
    clockInTime: '09:50 AM',
  },
  {
    id: 'carlos',
    name: 'Carlos',
    role: 'Assistant Manager',
    status: 'Late',
    currentShift: 'Lunch Shift (7:00 AM - 5:00PM)',
    currentAssignment: 'Floor Operation',
    stationTables: 'Branch Floor',
    clockInTime: '10:02 AM',
  },
];

export const INITIAL_KDS_TICKETS: KdsTicket[] = [
  {
    id: 'ticket-1',
    table: 'Table 12',
    orderNumber: 'ORD - 8821',
    timeAgo: '4m ago',
    server: 'Marco Vance',
    items: [
      { name: '2x Dry-Aged Prime Ribeye 14oz', category: 'MAIN', mod: 'MOD: Medium Rare, Truffle Butter' },
      { name: '2x Barolo DOCG Red Wine Glass', category: 'BEVERAGE' },
      { name: '1x Crispy Truffle Fries', category: 'SIDE', mod: 'MOD: Extra Parmesan' },
    ],
  },
  {
    id: 'ticket-2',
    table: 'Table 04',
    orderNumber: 'ORD - 8824',
    timeAgo: '8m ago',
    server: 'Elena Rostova',
    items: [
      { name: '2x Wild Mushroom Risotto', category: 'MAIN' },
      { name: '2x Pan-Seared Sea Bass', category: 'MAIN', mod: 'MOD: Lemon Herb Oil' },
      { name: '4x Aperol Spritz Signature', category: 'BEVERAGE' },
      { name: '1x Charcuterie & Cheese Board', category: 'APPETIZER' },
    ],
  },
  {
    id: 'ticket-3',
    table: 'VVIP Booth A',
    orderNumber: 'ORD - 8829',
    timeAgo: '16m ago',
    server: 'David Chen',
    items: [
      { name: '1x Tomahawk Wagyu Steak 32oz', category: 'MAIN', mod: 'MOD: Chef Medium' },
      { name: '2x Lobster Tail Flambe', category: 'MAIN' },
      { name: '1x Vintage Dom Perignon Champagne', category: 'ALCOHOL' },
      { name: '2x Truffle Mac & Cheese', category: 'SIDE' },
    ],
  },
  {
    id: 'ticket-4',
    table: 'Bar Spot 03',
    orderNumber: 'ORD - 8832',
    timeAgo: '2m ago',
    server: 'Alex (Bartender)',
    items: [
      { name: '2x Smoked Old Fashioned', category: 'ALCOHOL' },
      { name: '1x Wagyu Beef Sliders (3pcs)', category: 'APPETIZER' },
    ],
  },
  {
    id: 'ticket-5',
    table: 'Express Counter 02',
    orderNumber: 'ORD - 8834',
    timeAgo: '5m ago',
    server: 'Cashier Station',
    items: [
      { name: '1x Tavonza Signature Burger', category: 'MAIN', mod: 'MOD: Brioche Bun, No Pickles' },
      { name: '1x Fresh Lemon Mint Iced Tea', category: 'BEVERAGE' },
    ],
  },
];

// Payment Mock Data
export const mockPaymentSummaryKpi: PaymentSummaryKpi = {
  todaysTotal: '$636.00',
  transactionsCount: 8,
  pendingTotal: '$160.50',
  pendingCount: 2,
  completedTotal: '$475.50',
  completedCount: 4,
  failedTotal: '$636.00',
  failedCount: 1,
  cardReaderCount: 5,
  cashCount: 1,
};

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    orderNumber: '#10590',
    table: '#01',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Visa Card',
    status: 'Preparing',
    waiter: 'James',
    timestamp: '19 : 42 PM',
    partySize: 2,
    recordId: 'Pay-1058',
    servingCashier: 'James',
    posDetails: 'Visa Signature....4288',
  },
  {
    id: 'pay-2',
    orderNumber: '#10590',
    table: '#02',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Cash',
    status: 'Ready',
    waiter: 'Sara.',
    timestamp: '19 : 30 PM',
    partySize: 4,
    recordId: 'Pay-1059',
    servingCashier: 'Chloe',
    posDetails: 'Cash Drawer POS #1',
  },
  {
    id: 'pay-3',
    orderNumber: '#10590',
    table: '#03',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Digital Wallet',
    status: 'Pending',
    waiter: 'Sarah M.',
    timestamp: '19 : 25 PM',
    partySize: 2,
    recordId: 'Pay-1060',
    servingCashier: 'James',
    posDetails: 'Apple Pay / NFC Contactless',
  },
  {
    id: 'pay-4',
    orderNumber: '#10590',
    table: '#04',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Visa Card',
    status: 'Payment Pending',
    waiter: 'James',
    timestamp: '19 : 15 PM',
    partySize: 3,
    recordId: 'Pay-1061',
    servingCashier: 'James',
    posDetails: 'MasterCard Signature....9120',
  },
  {
    id: 'pay-5',
    orderNumber: '#10590',
    table: '#05',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Cash',
    status: 'Needs Attention',
    waiter: 'Sara',
    timestamp: '18 : 55 PM',
    partySize: 6,
    recordId: 'Pay-1062',
    servingCashier: 'Chloe',
    posDetails: 'Cash Tender ($50.00 bill)',
  },
  {
    id: 'pay-6',
    orderNumber: '#10590',
    table: '#06',
    customer: 'Sarah M.',
    amount: '$18.50',
    method: 'Digital Wallet',
    status: 'Ordering',
    waiter: 'James',
    timestamp: '18 : 45 PM',
    partySize: 2,
    recordId: 'Pay-1063',
    servingCashier: 'James',
    posDetails: 'Google Pay / NFC Terminal',
  },
];

// Menu Mock Data
export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Grilled Chicken',
    category: 'Mains - Grill',
    stationBadge: 'Grill',
    stationBadgeColor: 'bg-pink-400/10 text-pink-400',
    price: '$18.00',
    description: 'Flame-grilled marinated chicken breast served with rosemary butter and garlic roast potatoes.',
    status: 'Available',
    availability: 'In stock',
    modifiersCount: '2 group(s)',
    enabled: true,
  },
  {
    id: 'item-2',
    name: 'Truffle Mushroom Pasta',
    category: 'Mains - Pasta',
    stationBadge: 'Oven',
    stationBadgeColor: 'bg-fuchsia-500/10 text-fuchsia-400',
    price: '$22.50',
    description: 'Fresh tagliatelle with black truffle cream sauce, wild mushrooms, and shaved parmesan.',
    status: 'Available',
    availability: 'In stock',
    modifiersCount: '2 group(s)',
    enabled: true,
  },
  {
    id: 'item-3',
    name: 'Crispy Calamari',
    category: 'Starters',
    stationBadge: 'Fryer',
    stationBadgeColor: 'bg-yellow-400/10 text-yellow-400',
    price: '$14.00',
    description: 'Flash-fried tender calamari served with house garlic aioli and lemon wedges.',
    status: 'Available',
    availability: 'Low Stock (8 Left)',
    modifiersCount: '2 group(s)',
    enabled: true,
  },
  {
    id: 'item-4',
    name: 'Craft IPA Beer',
    category: 'Beverages',
    stationBadge: 'Bar',
    stationBadgeColor: 'bg-blue-400/10 text-blue-400',
    price: '$8.50',
    description: 'Locally brewed India Pale Ale with a bright citrus hop profile.',
    status: 'Available',
    availability: 'In stock',
    modifiersCount: '2 group(s)',
    enabled: true,
  },
  {
    id: 'item-5',
    name: 'New York Cheesecake',
    category: 'Desserts',
    stationBadge: 'Dessert Prep',
    stationBadgeColor: 'bg-pink-400/10 text-pink-400',
    price: '$9.50',
    description: 'Rich creamy cheesecake topped with fresh berry compote and biscuit crumb.',
    status: 'Disabled',
    availability: 'Out of stock',
    modifiersCount: '2 group(s)',
    enabled: false,
  },
];
